packages:
  - 'frontend/*'
  - 'scripts'
overrides:
  material-react-table: npm:@greenhat616/material-react-table@4.0.0
#patchedDependencies:
#  monaco-worker-manager@2.0.1: patches/monaco-worker-manager@2.0.1.patch
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  core-js-pure: true
  electron: true
  esbuild: true
  meta-json-schema: true
  oxc-resolver: true
minimumReleaseAgeExclude:
  - '@iconify/json@2.2.491'
  - '@inlang/paraglide-js@2.22.0'
  - '@tanstack/react-router@1.170.18'
  - '@tanstack/router-core@1.171.15'
  - '@tanstack/router-generator@1.167.19'
  - '@tanstack/router-plugin@1.168.20'
  - meta-json-schema@1.19.28
  - postcss@8.5.19
  - '@prettier/plugin-oxc@0.2.2'
  - prettier@3.9.6
