use super::{Ctx, MigrationState, MigrationStep, ModuleMigrator};
use anyhow::{Context, bail};
use chrono::{SecondsFormat, Utc};
use semver::Version;
use serde::{Deserialize, Serialize};
use std::{collections::BTreeMap, path::Path};

pub const STORE_SCHEMA_VERSION: u64 = 2;
pub const STORE_FILE_NAME: &str = "migration-state.yaml";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct AppMigrationState {
    pub last_succeeded: Option<Version>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct ModuleState {
    pub applied_revision: u64,
    pub baseline_revision: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TaskRecord {
    pub module: String,
    pub revision: u64,
    pub introduced_in: Version,
    pub state: MigrationState,
    pub started_at: Option<String>,
    pub finished_at: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MigrationStore {
    pub store_schema_version: u64,
    #[serde(default)]
    pub app: AppMigrationState,
    #[serde(default)]
    pub modules: BTreeMap<String, ModuleState>,
    #[serde(default)]
    pub tasks: BTreeMap<String, TaskRecord>,
}

impl Default for MigrationStore {
    fn default() -> Self {
        Self {
            store_schema_version: STORE_SCHEMA_VERSION,
            app: AppMigrationState::default(),
            modules: BTreeMap::new(),
            tasks: BTreeMap::new(),
        }
    }
}

impl MigrationStore {
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }

        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read migration state {}", path.display()))?;
        let store: Self = serde_yaml::from_str(&raw)
            .with_context(|| format!("failed to parse migration state {}", path.display()))?;
        if store.store_schema_version != STORE_SCHEMA_VERSION {
            bail!(
                "unsupported migration store schema version {}",
                store.store_schema_version
            );
        }
        Ok(store)
    }

    pub fn flush_atomic(&self, path: &Path) -> anyhow::Result<()> {
        let content = serde_yaml::to_string(self).context("failed to serialize migration state")?;
        let mut bytes =
            b"# This file is generated by the migration system, do not edit it manually.\n"
                .to_vec();
        bytes.extend_from_slice(content.as_bytes());
        super::fs::atomic_write(path, &bytes).context("failed to persist migration state")
    }

    pub fn task_state(&self, id: &str) -> Option<MigrationState> {
        self.tasks.get(id).map(|task| task.state)
    }

    pub fn module_state(&self, module: &str) -> ModuleState {
        self.modules.get(module).copied().unwrap_or_default()
    }

    pub fn ensure_module(
        &mut self,
        module: &dyn ModuleMigrator,
        ctx: &Ctx,
    ) -> anyhow::Result<bool> {
        if self.modules.contains_key(module.module()) {
            return Ok(false);
        }

        let baseline = module.detect_baseline(ctx)?;
        self.modules.insert(
            module.module().to_string(),
            ModuleState {
                applied_revision: baseline,
                baseline_revision: baseline,
            },
        );
        Ok(true)
    }

    pub fn mark_in_progress(&mut self, step: &dyn MigrationStep) {
        let now = timestamp();
        self.tasks.insert(
            step.id().to_string(),
            TaskRecord {
                module: step.module().to_string(),
                revision: step.revision(),
                introduced_in: step.introduced_in().clone(),
                state: MigrationState::InProgress,
                started_at: Some(now),
                finished_at: None,
                error: None,
            },
        );
    }

    pub fn mark_completed(&mut self, step: &dyn MigrationStep) {
        let now = timestamp();
        let task = self
            .tasks
            .entry(step.id().to_string())
            .or_insert_with(|| TaskRecord {
                module: step.module().to_string(),
                revision: step.revision(),
                introduced_in: step.introduced_in().clone(),
                state: MigrationState::NotStarted,
                started_at: Some(now.clone()),
                finished_at: None,
                error: None,
            });

        task.module = step.module().to_string();
        task.revision = step.revision();
        task.introduced_in = step.introduced_in().clone();
        task.state = MigrationState::Completed;
        task.started_at.get_or_insert_with(|| now.clone());
        task.finished_at = Some(now);
        task.error = None;
    }

    pub fn mark_failed(&mut self, step: &dyn MigrationStep, error: &anyhow::Error) {
        let now = timestamp();
        let task = self
            .tasks
            .entry(step.id().to_string())
            .or_insert_with(|| TaskRecord {
                module: step.module().to_string(),
                revision: step.revision(),
                introduced_in: step.introduced_in().clone(),
                state: MigrationState::NotStarted,
                started_at: Some(now.clone()),
                finished_at: None,
                error: None,
            });

        task.module = step.module().to_string();
        task.revision = step.revision();
        task.introduced_in = step.introduced_in().clone();
        task.state = MigrationState::Failed;
        task.started_at.get_or_insert_with(|| now.clone());
        task.finished_at = Some(now);
        task.error = Some(format!("{error:#}"));
    }

    pub fn bump_module(&mut self, module: &str) {
        let baseline = self
            .modules
            .get(module)
            .map(|state| state.baseline_revision)
            .unwrap_or_default();
        let mut applied = baseline;
        loop {
            let next = applied + 1;
            let completed = self.tasks.values().any(|task| {
                task.module == module
                    && task.revision == next
                    && task.state == MigrationState::Completed
            });
            if completed {
                applied = next;
            } else {
                break;
            }
        }
        self.modules
            .entry(module.to_string())
            .or_default()
            .applied_revision = applied;
    }

    pub fn set_last_succeeded(&mut self, version: Version) {
        self.app.last_succeeded = Some(version);
    }
}

fn timestamp() -> String {
    Utc::now().to_rfc3339_opts(SecondsFormat::Millis, true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn atomic_write_replaces_existing_store() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join(STORE_FILE_NAME);

        let mut store = MigrationStore::default();
        store.set_last_succeeded(Version::parse("0.22.4").unwrap());
        store.flush_atomic(&path).unwrap();

        store.modules.insert(
            "typed_config".to_string(),
            ModuleState {
                applied_revision: 2,
                baseline_revision: 0,
            },
        );
        store.flush_atomic(&path).unwrap();

        let loaded = MigrationStore::load(&path).unwrap();
        assert_eq!(
            loaded.modules.get("typed_config").copied(),
            Some(ModuleState {
                applied_revision: 2,
                baseline_revision: 0,
            })
        );
    }

    fn completed_task(module: &str, revision: u64) -> TaskRecord {
        TaskRecord {
            module: module.to_string(),
            revision,
            introduced_in: Version::parse("0.22.4").unwrap(),
            state: MigrationState::Completed,
            started_at: None,
            finished_at: None,
            error: None,
        }
    }

    #[test]
    fn bump_module_advances_only_contiguous_completed() {
        let mut store = MigrationStore::default();
        store
            .modules
            .insert("typed_config".to_string(), ModuleState::default());

        store.tasks.insert(
            "typed_config/repair".to_string(),
            completed_task("typed_config", 2),
        );
        store.bump_module("typed_config");
        assert_eq!(store.module_state("typed_config").applied_revision, 0);

        store.tasks.insert(
            "typed_config/split".to_string(),
            completed_task("typed_config", 1),
        );
        store.bump_module("typed_config");
        assert_eq!(store.module_state("typed_config").applied_revision, 2);
    }
}
