/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as mainRouteRouteImport } from './pages/(main)/route'
import { Route as legacyRouteRouteImport } from './pages/(legacy)/route'
import { Route as legacyIndexRouteImport } from './pages/(legacy)/index'
import { Route as legacySettingsRouteImport } from './pages/(legacy)/settings'
import { Route as legacyRulesRouteImport } from './pages/(legacy)/rules'
import { Route as legacyProxiesRouteImport } from './pages/(legacy)/proxies'
import { Route as legacyProvidersRouteImport } from './pages/(legacy)/providers'
import { Route as legacyProfilesRouteImport } from './pages/(legacy)/profiles'
import { Route as legacyLogsRouteImport } from './pages/(legacy)/logs'
import { Route as legacyDashboardRouteImport } from './pages/(legacy)/dashboard'
import { Route as legacyConnectionsRouteImport } from './pages/(legacy)/connections'
import { Route as mainMainIndexRouteImport } from './pages/(main)/main/index'
import { Route as mainMainProvidersRouteRouteImport } from './pages/(main)/main/providers/route'
import { Route as mainMainProvidersIndexRouteImport } from './pages/(main)/main/providers/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyRouteRoute = legacyRouteRouteImport.update({
  id: '/(legacy)',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyIndexRoute = legacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacySettingsRoute = legacySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyRulesRoute = legacyRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyProxiesRoute = legacyProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyProvidersRoute = legacyProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyProfilesRoute = legacyProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyLogsRoute = legacyLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyDashboardRoute = legacyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyConnectionsRoute = legacyConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => legacyRouteRoute,
} as any)
const mainMainIndexRoute = mainMainIndexRouteImport.update({
  id: '/main/',
  path: '/main/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMainProvidersRouteRoute = mainMainProvidersRouteRouteImport.update({
  id: '/main/providers',
  path: '/main/providers',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMainProvidersIndexRoute = mainMainProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainMainProvidersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/connections': typeof legacyConnectionsRoute
  '/dashboard': typeof legacyDashboardRoute
  '/logs': typeof legacyLogsRoute
  '/profiles': typeof legacyProfilesRoute
  '/providers': typeof legacyProvidersRoute
  '/proxies': typeof legacyProxiesRoute
  '/rules': typeof legacyRulesRoute
  '/settings': typeof legacySettingsRoute
  '/': typeof legacyIndexRoute
  '/main/providers': typeof mainMainProvidersRouteRouteWithChildren
  '/main/': typeof mainMainIndexRoute
  '/main/providers/': typeof mainMainProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/connections': typeof legacyConnectionsRoute
  '/dashboard': typeof legacyDashboardRoute
  '/logs': typeof legacyLogsRoute
  '/profiles': typeof legacyProfilesRoute
  '/providers': typeof legacyProvidersRoute
  '/proxies': typeof legacyProxiesRoute
  '/rules': typeof legacyRulesRoute
  '/settings': typeof legacySettingsRoute
  '/': typeof legacyIndexRoute
  '/main': typeof mainMainIndexRoute
  '/main/providers': typeof mainMainProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(legacy)': typeof legacyRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(legacy)/connections': typeof legacyConnectionsRoute
  '/(legacy)/dashboard': typeof legacyDashboardRoute
  '/(legacy)/logs': typeof legacyLogsRoute
  '/(legacy)/profiles': typeof legacyProfilesRoute
  '/(legacy)/providers': typeof legacyProvidersRoute
  '/(legacy)/proxies': typeof legacyProxiesRoute
  '/(legacy)/rules': typeof legacyRulesRoute
  '/(legacy)/settings': typeof legacySettingsRoute
  '/(legacy)/': typeof legacyIndexRoute
  '/(main)/main/providers': typeof mainMainProvidersRouteRouteWithChildren
  '/(main)/main/': typeof mainMainIndexRoute
  '/(main)/main/providers/': typeof mainMainProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/connections'
    | '/dashboard'
    | '/logs'
    | '/profiles'
    | '/providers'
    | '/proxies'
    | '/rules'
    | '/settings'
    | '/'
    | '/main/providers'
    | '/main/'
    | '/main/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connections'
    | '/dashboard'
    | '/logs'
    | '/profiles'
    | '/providers'
    | '/proxies'
    | '/rules'
    | '/settings'
    | '/'
    | '/main'
    | '/main/providers'
  id:
    | '__root__'
    | '/(legacy)'
    | '/(main)'
    | '/(legacy)/connections'
    | '/(legacy)/dashboard'
    | '/(legacy)/logs'
    | '/(legacy)/profiles'
    | '/(legacy)/providers'
    | '/(legacy)/proxies'
    | '/(legacy)/rules'
    | '/(legacy)/settings'
    | '/(legacy)/'
    | '/(main)/main/providers'
    | '/(main)/main/'
    | '/(main)/main/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  legacyRouteRoute: typeof legacyRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)': {
      id: '/(legacy)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/': {
      id: '/(legacy)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof legacyIndexRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/settings': {
      id: '/(legacy)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof legacySettingsRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/rules': {
      id: '/(legacy)/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof legacyRulesRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/proxies': {
      id: '/(legacy)/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof legacyProxiesRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/providers': {
      id: '/(legacy)/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof legacyProvidersRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/profiles': {
      id: '/(legacy)/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof legacyProfilesRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/logs': {
      id: '/(legacy)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof legacyLogsRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/dashboard': {
      id: '/(legacy)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof legacyDashboardRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/connections': {
      id: '/(legacy)/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof legacyConnectionsRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(main)/main/': {
      id: '/(main)/main/'
      path: '/main'
      fullPath: '/main/'
      preLoaderRoute: typeof mainMainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/main/providers': {
      id: '/(main)/main/providers'
      path: '/main/providers'
      fullPath: '/main/providers'
      preLoaderRoute: typeof mainMainProvidersRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/main/providers/': {
      id: '/(main)/main/providers/'
      path: '/'
      fullPath: '/main/providers/'
      preLoaderRoute: typeof mainMainProvidersIndexRouteImport
      parentRoute: typeof mainMainProvidersRouteRoute
    }
  }
}

interface legacyRouteRouteChildren {
  legacyConnectionsRoute: typeof legacyConnectionsRoute
  legacyDashboardRoute: typeof legacyDashboardRoute
  legacyLogsRoute: typeof legacyLogsRoute
  legacyProfilesRoute: typeof legacyProfilesRoute
  legacyProvidersRoute: typeof legacyProvidersRoute
  legacyProxiesRoute: typeof legacyProxiesRoute
  legacyRulesRoute: typeof legacyRulesRoute
  legacySettingsRoute: typeof legacySettingsRoute
  legacyIndexRoute: typeof legacyIndexRoute
}

const legacyRouteRouteChildren: legacyRouteRouteChildren = {
  legacyConnectionsRoute: legacyConnectionsRoute,
  legacyDashboardRoute: legacyDashboardRoute,
  legacyLogsRoute: legacyLogsRoute,
  legacyProfilesRoute: legacyProfilesRoute,
  legacyProvidersRoute: legacyProvidersRoute,
  legacyProxiesRoute: legacyProxiesRoute,
  legacyRulesRoute: legacyRulesRoute,
  legacySettingsRoute: legacySettingsRoute,
  legacyIndexRoute: legacyIndexRoute,
}

const legacyRouteRouteWithChildren = legacyRouteRoute._addFileChildren(
  legacyRouteRouteChildren,
)

interface mainMainProvidersRouteRouteChildren {
  mainMainProvidersIndexRoute: typeof mainMainProvidersIndexRoute
}

const mainMainProvidersRouteRouteChildren: mainMainProvidersRouteRouteChildren =
  {
    mainMainProvidersIndexRoute: mainMainProvidersIndexRoute,
  }

const mainMainProvidersRouteRouteWithChildren =
  mainMainProvidersRouteRoute._addFileChildren(
    mainMainProvidersRouteRouteChildren,
  )

interface mainRouteRouteChildren {
  mainMainProvidersRouteRoute: typeof mainMainProvidersRouteRouteWithChildren
  mainMainIndexRoute: typeof mainMainIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainMainProvidersRouteRoute: mainMainProvidersRouteRouteWithChildren,
  mainMainIndexRoute: mainMainIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  legacyRouteRoute: legacyRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
