import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

interface ProfileItem {
  uid: string;
  name: string;
}

interface ProfilesResponse {
  current: string | null;
  items: ProfileItem[];
}

type CoreState = 'Running' | { Stopped: string | null };

async function invoke<T>(command: string, args?: Record<string, unknown>) {
  return browser.execute(
    async (name, payload) => {
      const tauri = (
        window as typeof window & {
          __TAURI_INTERNALS__: {
            invoke: (
              command: string,
              args?: Record<string, unknown>,
            ) => Promise<T>;
          };
        }
      ).__TAURI_INTERNALS__;
      return tauri.invoke(name, payload);
    },
    command,
    args,
  );
}

async function readProfiles(): Promise<ProfilesResponse> {
  return invoke<ProfilesResponse>('get_profiles');
}

async function waitForCoreRunning(): Promise<void> {
  let lastState = 'unknown';
  await browser.waitUntil(
    async () => {
      const [state] =
        await invoke<[CoreState, number, string]>('get_core_status');
      lastState = JSON.stringify(state);
      return state === 'Running';
    },
    {
      timeout: 30_000,
      timeoutMsg: `The core did not become running. Last state: ${lastState}`,
    },
  );
}

function runtimePaths() {
  const runtimeRoot = process.env.CHIMERA_E2E_RUNTIME_DIR;
  assert.ok(runtimeRoot, 'CHIMERA_E2E_RUNTIME_DIR is not configured.');
  const runtimeDirectory = path.join(runtimeRoot, 'config', 'runtime');
  return {
    product: path.join(runtimeDirectory, 'clash-config.yaml'),
    candidates: path.join(runtimeDirectory, '.candidates'),
  };
}

function assertRuntimeProductIsPromoted(): void {
  const { product, candidates } = runtimePaths();
  assert.equal(
    fs.existsSync(product),
    true,
    'The promoted runtime product is missing.',
  );
  const productBytes = fs.readFileSync(product, 'utf8');
  assert.match(productBytes, /^# Generated by Clash Chimera\r?\n\r?\n/);
  assert.match(productBytes, /external-controller:/);

  const candidateFiles = fs.existsSync(candidates)
    ? fs.readdirSync(candidates).filter((name) => name.startsWith('candidate-'))
    : [];
  assert.deepEqual(
    candidateFiles,
    [],
    'A successful restart left candidate files behind.',
  );
}

async function openLocalProfileForm() {
  const currentUrl = new URL(await browser.getUrl());
  currentUrl.pathname = '/main/profiles/profile';
  currentUrl.search = '?action=ImportLocalProfile';
  await browser.url(currentUrl.href);

  const nameInput = await $('input[name="name"]');
  await nameInput.waitForDisplayed({ timeout: 15_000 });
  return nameInput;
}

describe('Chimera profile runtime product lifecycle', () => {
  it('checks, promotes and starts the exact product when the first local profile is created', async () => {
    const profileName = `runtime-product-${Date.now()}`;
    let createdUid: string | null = null;

    await waitForCoreRunning();

    try {
      const nameInput = await openLocalProfileForm();
      await nameInput.setValue(profileName);

      const descriptionInput = await $('textarea[name="desc"]');
      await descriptionInput.setValue(
        'Exercises the checked runtime product lifecycle.',
      );

      const okButton = await $('button=OK');
      await okButton.waitForClickable({ timeout: 15_000 });
      await okButton.click();

      await browser.waitUntil(async () => !(await nameInput.isExisting()), {
        timeout: 45_000,
        timeoutMsg:
          'The local profile dialog did not close after the create transaction finished.',
      });

      await browser.waitUntil(
        async () => {
          const profiles = await readProfiles();
          const created = profiles.items.find(
            (item) => item.name === profileName,
          );
          createdUid = created?.uid ?? null;
          return Boolean(createdUid && profiles.current === createdUid);
        },
        {
          timeout: 45_000,
          timeoutMsg: 'The local profile was not created and activated.',
        },
      );

      assert.ok(createdUid);
      await waitForCoreRunning();
      assertRuntimeProductIsPromoted();

      const card = await $(
        `[data-slot="profile-card"][data-profile-uid="${createdUid}"]`,
      );
      await card.waitForDisplayed({ timeout: 15_000 });
      assert.equal(await card.getAttribute('data-profile-active'), 'true');
      assert.equal(
        await card
          .$('[data-slot="profile-card-active-background"]')
          .isExisting(),
        true,
      );

      await browser.refresh();
      await browser.waitUntil(
        async () => {
          const profiles = await readProfiles();
          return profiles.current === createdUid;
        },
        {
          timeout: 30_000,
          timeoutMsg: 'The active profile was not persisted after refresh.',
        },
      );
      await waitForCoreRunning();
      assertRuntimeProductIsPromoted();

      const refreshedCard = await $(
        `[data-slot="profile-card"][data-profile-uid="${createdUid}"]`,
      );
      await refreshedCard.waitForDisplayed({ timeout: 15_000 });
      assert.equal(
        await refreshedCard.getAttribute('data-profile-active'),
        'true',
      );
    } finally {
      if (!createdUid) {
        const profiles = await readProfiles().catch(() => null);
        createdUid =
          profiles?.items.find((item) => item.name === profileName)?.uid ??
          null;
      }

      if (createdUid) {
        await invoke<null>('delete_profile', { uid: createdUid });
        await browser.waitUntil(
          async () => {
            const profiles = await readProfiles();
            return !profiles.items.some((item) => item.uid === createdUid);
          },
          {
            timeout: 45_000,
            timeoutMsg: 'The runtime product test profile was not removed.',
          },
        );
        await waitForCoreRunning();
        assertRuntimeProductIsPromoted();
      }
    }
  });
});
