import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import type { MutationOutcome } from '../../frontend/interface/src/ipc/bindings.js';
import {
  appliedValue,
  committedValue,
  invoke,
  readProfiles,
  withCleanup,
} from './profile-fixtures.js';

type CoreState = 'Running' | { Stopped: string | null };

async function waitForCoreRunning(): Promise<void> {
  let lastState = 'unknown';
  await browser.waitUntil(
    async () => {
      const [state] =
        await invoke<[CoreState, number, string]>('get_core_status');
      lastState = JSON.stringify(state);
      return state === 'Running';
    },
    {
      timeout: 30_000,
      timeoutMsg: `The core did not become running. Last state: ${lastState}`,
    },
  );
}

function runtimePaths() {
  const runtimeRoot = process.env.CHIMERA_E2E_RUNTIME_DIR;
  assert.ok(runtimeRoot, 'CHIMERA_E2E_RUNTIME_DIR is not configured.');
  const runtimeDirectory = path.join(runtimeRoot, 'config', 'runtime');
  return {
    product: path.join(runtimeDirectory, 'clash-config.yaml'),
    candidates: path.join(runtimeDirectory, '.candidates'),
  };
}

function assertRuntimeProductIsPromoted(): void {
  const { product, candidates } = runtimePaths();
  assert.equal(
    fs.existsSync(product),
    true,
    'The promoted runtime product is missing.',
  );
  const productBytes = fs.readFileSync(product, 'utf8');
  assert.match(productBytes, /^# Generated by Clash Chimera\r?\n\r?\n/);
  assert.match(productBytes, /external-controller:/);

  const candidateFiles = fs.existsSync(candidates)
    ? fs.readdirSync(candidates).filter((name) => name.startsWith('candidate-'))
    : [];
  assert.deepEqual(
    candidateFiles,
    [],
    'A successful restart left candidate files behind.',
  );
}

async function openLocalProfileForm() {
  const currentUrl = new URL(await browser.getUrl());
  currentUrl.pathname = '/main/profiles/profile';
  currentUrl.search = '?action=ImportLocalProfile';
  await browser.url(currentUrl.href);

  const nameInput = await $('input[name="name"]');
  await nameInput.waitForDisplayed({ timeout: 15_000 });
  return nameInput;
}

async function captureFailureBeforeCleanup(
  profileName: string,
  error: unknown,
): Promise<void> {
  const artifactDirectory = process.env.CHIMERA_E2E_ARTIFACT_DIR;
  if (!artifactDirectory || !browser.sessionId) return;

  const runId = path.basename(
    process.env.CHIMERA_E2E_RUNTIME_DIR ?? `local-${process.pid}`,
  );
  const artifactName =
    `profile-runtime-product-${runId}-${profileName}-${process.pid}-${Date.now()}`.replace(
      /[^a-z0-9._-]+/gi,
      '-',
    );
  const artifactBase = path.join(artifactDirectory, artifactName);
  const captureErrors: string[] = [];
  try {
    fs.mkdirSync(artifactDirectory, { recursive: true });
  } catch (captureError) {
    process.stderr.write(
      `Could not create failure evidence directory: ${String(captureError)}\n`,
    );
    return;
  }

  await browser
    .saveScreenshot(`${artifactBase}.before-cleanup.png`)
    .catch((captureError) => captureErrors.push(String(captureError)));
  await browser
    .getPageSource()
    .then((source) =>
      fs.writeFileSync(`${artifactBase}.before-cleanup.html`, source),
    )
    .catch((captureError) => captureErrors.push(String(captureError)));
  try {
    fs.writeFileSync(
      `${artifactBase}.before-cleanup.error.txt`,
      error instanceof Error ? (error.stack ?? error.message) : String(error),
    );
  } catch (captureError) {
    captureErrors.push(String(captureError));
  }
  if (captureErrors.length > 0) {
    try {
      fs.writeFileSync(
        `${artifactBase}.capture-error.txt`,
        captureErrors.join('\n'),
      );
    } catch (captureError) {
      process.stderr.write(
        `Could not save capture errors: ${String(captureError)}\n`,
      );
    }
  }
}

describe('Chimera profile runtime product lifecycle', () => {
  // Contract: from the isolated E2E runtime with a healthy core, create one
  // uniquely named local Profile through the UI. The Profiles document proves
  // its UID became current, and the generated runtime file proves promotion.
  // A stored-but-inactive Profile or missing product fails these checks.
  // Cleanup restores the original selection before deleting only this Profile.
  it('checks, promotes and starts the exact product when the first local profile is created', async () => {
    const profileName = `runtime-product-${Date.now()}`;
    const initialProfiles = await readProfiles();
    assert.equal(
      initialProfiles.items.some((item) => item.name === profileName),
      false,
      'The isolated runtime already contains a Profile owned by this test.',
    );
    let createdUid: string | null = null;

    await withCleanup('runtime product Profile lifecycle', async (defer) => {
      const findCreatedUid = async (): Promise<string | null> => {
        const profiles = await readProfiles();
        const created = profiles.items.find(
          (item) => item.uid === createdUid || item.name === profileName,
        );
        createdUid = created?.uid ?? null;
        return createdUid;
      };

      defer('restore the original Profile selection', async () => {
        const profiles = await readProfiles();
        if (profiles.current === initialProfiles.current) return;

        appliedValue(
          await invoke<MutationOutcome<null>>('activate_profile', {
            uid: initialProfiles.current,
          }),
          'Original Profile selection restoration',
        );
        await browser.waitUntil(
          async () =>
            (await readProfiles()).current === initialProfiles.current,
          {
            timeout: 30_000,
            timeoutMsg: 'The original Profile selection was not restored.',
          },
        );
        await waitForCoreRunning();
      });

      defer('delete the test Profile', async () => {
        const uid = await findCreatedUid();
        if (!uid) return;

        const profiles = await readProfiles();
        assert.notEqual(
          profiles.current,
          uid,
          'The test Profile is still active and cannot be deleted safely.',
        );
        committedValue(
          await invoke<MutationOutcome<null>>('delete_profile', { uid }),
          'Runtime product test Profile deletion',
        );
        await browser.waitUntil(
          async () =>
            !(await readProfiles()).items.some((item) => item.uid === uid),
          {
            timeout: 45_000,
            timeoutMsg: 'The runtime product test Profile was not removed.',
          },
        );
        await waitForCoreRunning();
        assertRuntimeProductIsPromoted();
      });

      try {
        await waitForCoreRunning();
        const nameInput = await openLocalProfileForm();
        await nameInput.setValue(profileName);

        const descriptionInput = await $('textarea[name="desc"]');
        await descriptionInput.setValue(
          'Exercises the checked runtime product lifecycle.',
        );

        const okButton = await $('button=OK');
        await okButton.waitForClickable({ timeout: 15_000 });
        await okButton.click();

        await browser.waitUntil(async () => !(await nameInput.isExisting()), {
          timeout: 45_000,
          timeoutMsg:
            'The local profile dialog did not close after the create transaction finished.',
        });

        await browser.waitUntil(
          async () => {
            const profiles = await readProfiles();
            const created = profiles.items.find(
              (item) => item.name === profileName,
            );
            createdUid = created?.uid ?? null;
            return Boolean(createdUid && profiles.current === createdUid);
          },
          {
            timeout: 45_000,
            timeoutMsg: 'The local profile was not created and activated.',
          },
        );

        assert.ok(createdUid);
        await waitForCoreRunning();
        assertRuntimeProductIsPromoted();

        const card = await $(
          `[data-slot="profile-card"][data-profile-uid="${createdUid}"]`,
        );
        await card.waitForDisplayed({ timeout: 15_000 });
        assert.equal(await card.getAttribute('data-profile-active'), 'true');
        assert.equal(
          await card
            .$('[data-slot="profile-card-active-background"]')
            .isExisting(),
          true,
        );

        await browser.refresh();
        await browser.waitUntil(
          async () => {
            const profiles = await readProfiles();
            return profiles.current === createdUid;
          },
          {
            timeout: 30_000,
            timeoutMsg: 'The active profile was not persisted after refresh.',
          },
        );
        await waitForCoreRunning();
        assertRuntimeProductIsPromoted();

        const refreshedCard = await $(
          `[data-slot="profile-card"][data-profile-uid="${createdUid}"]`,
        );
        await refreshedCard.waitForDisplayed({ timeout: 15_000 });
        assert.equal(
          await refreshedCard.getAttribute('data-profile-active'),
          'true',
        );
      } catch (error) {
        await captureFailureBeforeCleanup(profileName, error);
        throw error;
      }
    });
  });
});
