/* oxlint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
  greet: (name: string) => __TAURI_INVOKE<string>('greet', { name }),
  getSysProxy: () =>
    typedError<GetSysProxyResponse, string>(__TAURI_INVOKE('get_sys_proxy')),
  getProfiles: () =>
    typedError<ProfileDocument_Serialize, string>(
      __TAURI_INVOKE('get_profiles'),
    ),
  getRuntimeTransformDiagnostics: () =>
    typedError<
      {
        revision: number;
        output: PostProcessingOutput;
        failure: RuntimeTransformFailureDiagnostics | null;
      } | null,
      string
    >(__TAURI_INVOKE('get_runtime_transform_diagnostics')),
  getRuntimeConfig: () =>
    typedError<any | null, string>(__TAURI_INVOKE('get_runtime_config')),
  getRuntimeYaml: () =>
    typedError<string, string>(__TAURI_INVOKE('get_runtime_yaml')),
  getRuntimeExists: () =>
    typedError<string[], string>(__TAURI_INVOKE('get_runtime_exists')),
  inspectRuntime: () =>
    typedError<
      {
        snapshot_id: string;
        revision: string;
        target_core: string;
        root_id: number;
        nodes: RuntimeInspectionNode[];
      } | null,
      string
    >(__TAURI_INVOKE('inspect_runtime')),
  inspectRuntimeNode: (snapshotId: string, nodeId: number) =>
    typedError<RuntimeInspectionContent, string>(
      __TAURI_INVOKE('inspect_runtime_node', { snapshotId, nodeId }),
    ),
  getPostprocessingOutput: () =>
    typedError<PostProcessingOutput, string>(
      __TAURI_INVOKE('get_postprocessing_output'),
    ),
  flushSystemDnsCache: () =>
    typedError<null, string>(__TAURI_INVOKE('flush_system_dns_cache')),
  probeNetwork: (request: NetworkProbeRequest) =>
    typedError<NetworkProbeResult, string>(
      __TAURI_INVOKE('probe_network', { request }),
    ),
  /**  later: check in the frontend */
  getPendingDeepLinks: () =>
    typedError<PendingDeepLinkEntry[], string>(
      __TAURI_INVOKE('get_pending_deep_links'),
    ),
  claimPendingDeepLink: (id: number) =>
    typedError<boolean, string>(
      __TAURI_INVOKE('claim_pending_deep_link', { id }),
    ),
  importProfile: (
    url: string,
    name: string | null,
    option: {
      user_agent?: string | null;
      with_proxy: boolean | null;
      self_proxy: boolean | null;
      update_interval_minutes: number | null;
    } | null,
  ) =>
    typedError<MutationOutcome<ProfileId>, string>(
      __TAURI_INVOKE('import_profile', { url, name, option }),
    ),
  importProfileWithMode: (
    url: string,
    name: string | null,
    option: {
      user_agent?: string | null;
      with_proxy: boolean | null;
      self_proxy: boolean | null;
      update_interval_minutes: number | null;
    } | null,
    mode: RemoteProfileImportMode,
  ) =>
    typedError<MutationOutcome<ProfileId>, string>(
      __TAURI_INVOKE('import_profile_with_mode', { url, name, option, mode }),
    ),
  viewProfile: (uid: string) =>
    typedError<null, string>(__TAURI_INVOKE('view_profile', { uid })),
  reorderProfile: (activeId: string, overId: string) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('reorder_profile', { activeId, overId }),
    ),
  reorderProfilesByList: (list: string[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('reorder_profiles_by_list', { list }),
    ),
  activateProfile: (uid: string | null) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('activate_profile', { uid }),
    ),
  setProfileValidFields: (fields: string[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('set_profile_valid_fields', { fields }),
    ),
  setGlobalTransforms: (ids: ProfileId[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('set_global_transforms', { ids }),
    ),
  patchProfileMetadata: (
    uid: string,
    patch: ProfileMetadataPatch_Deserialize,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('patch_profile_metadata', { uid, patch }),
    ),
  patchRemoteProfileOptions: (
    uid: string,
    patch: RemoteProfileOptionsPatch_Deserialize,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('patch_remote_profile_options', { uid, patch }),
    ),
  replaceProfileDefinition: (
    uid: string,
    definition: ProfileDefinition_Deserialize,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('replace_profile_definition', { uid, definition }),
    ),
  updateProfile: (
    uid: string,
    option: {
      user_agent?: string | null;
      with_proxy: boolean | null;
      self_proxy: boolean | null;
      update_interval_minutes: number | null;
    } | null,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('update_profile', { uid, option }),
    ),
  deleteProfile: (uid: string) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('delete_profile', { uid }),
    ),
  readProfileFile: (uid: string) =>
    typedError<string, string>(__TAURI_INVOKE('read_profile_file', { uid })),
  saveProfileFile: (uid: string, fileData: string) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('save_profile_file', { uid, fileData }),
    ),
  /**  create a new profile */
  createProfile: (
    request: NewProfileRequest_Deserialize,
    fileData: string | null,
  ) =>
    typedError<MutationOutcome<ProfileId>, string>(
      __TAURI_INVOKE('create_profile', { request, fileData }),
    ),
  createEditorWindow: (windowType: EditorWindowType, uid: string | null) =>
    typedError<null, string>(
      __TAURI_INVOKE('create_editor_window', { windowType, uid }),
    ),
  getVergeConfig: () =>
    typedError<IVerge_Serialize, string>(__TAURI_INVOKE('get_verge_config')),
  getHotkeyFunctions: () => __TAURI_INVOKE<string[]>('get_hotkey_functions'),
  patchVergeConfig: (payload: IVerge_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_verge_config', { payload })),
  getClashInfo: () =>
    typedError<ClashInfo, string>(__TAURI_INVOKE('get_clash_info')),
  patchClashConfig: (payload: PatchRuntimeConfig_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_clash_config', { payload })),
  patchClashCoreConfig: (payload: PatchClashCoreConfig_Deserialize) =>
    typedError<null, string>(
      __TAURI_INVOKE('patch_clash_core_config', { payload }),
    ),
  getProxies: () =>
    typedError<Proxies_Serialize, string>(__TAURI_INVOKE('get_proxies')),
  selectProxy: (group: string, name: string) =>
    typedError<null, string>(__TAURI_INVOKE('select_proxy', { group, name })),
  changeClashCore: (
    clashCore:
      | 'clash'
      | 'clash-premium'
      | 'clash-rs'
      | 'mihomo'
      | 'clash-meta'
      | 'chimera-client'
      | 'chimera'
      | 'chimera_client'
      | 'mihomo-alpha'
      | 'clash-rs-alpha'
      | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE('change_clash_core', { clashCore }),
    ),
  getCoreStatus: () =>
    typedError<[CoreState, number, RunType], string>(
      __TAURI_INVOKE('get_core_status'),
    ),
  getCoreLifecycleStatus: () =>
    typedError<CoreLifecycleStatus, string>(
      __TAURI_INVOKE('get_core_lifecycle_status'),
    ),
  urlDelayTest: (url: string, expectedStatus: number) =>
    typedError<number | null, string>(
      __TAURI_INVOKE('url_delay_test', { url, expectedStatus }),
    ),
  getIpsbAsn: () =>
    typedError<IpsbResponse, string>(__TAURI_INVOKE('get_ipsb_asn')),
  invokeUwpTool: () =>
    typedError<null, string>(__TAURI_INVOKE('invoke_uwp_tool')),
  collectLogs: () => typedError<null, string>(__TAURI_INVOKE('collect_logs')),
  collectEnvs: () =>
    typedError<EnvInfo, string>(__TAURI_INVOKE('collect_envs')),
  getCustomAppDir: () =>
    typedError<string | null, string>(__TAURI_INVOKE('get_custom_app_dir')),
  setCustomAppDir: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE('set_custom_app_dir', { path })),
  clashApiGetConfigs: () =>
    typedError<ClashRuntimeConfig, string>(
      __TAURI_INVOKE('clash_api_get_configs'),
    ),
  clashApiGetProxyDelay: (name: string, url: string | null) =>
    typedError<DelayRes, string>(
      __TAURI_INVOKE('clash_api_get_proxy_delay', { name, url }),
    ),
  clashApiGetGroupDelay: (group: string, url: string | null) =>
    typedError<{ [key in string]: number }, string>(
      __TAURI_INVOKE('clash_api_get_group_delay', { group, url }),
    ),
  clashApiDeleteConnections: (id: string | null) =>
    typedError<null, string>(
      __TAURI_INVOKE('clash_api_delete_connections', { id }),
    ),
  getTrafficSummary: () =>
    typedError<TrafficSummary, string>(__TAURI_INVOKE('get_traffic_summary')),
  queryTrafficReport: (request: ReportRequest) =>
    typedError<TrafficReport, string>(
      __TAURI_INVOKE('query_traffic_report', { request }),
    ),
  queryTrafficUsage: (
    query: TrafficQuery,
    groupBy: Dimension,
    metric: Metric,
    after: {
      usage: Usage;
      key: string;
    } | null,
    limit: number,
  ) =>
    typedError<UsagePage, string>(
      __TAURI_INVOKE('query_traffic_usage', {
        query,
        groupBy,
        metric,
        after,
        limit,
      }),
    ),
  queryTrafficUsageByKeys: (
    query: TrafficQuery,
    groupBy: Dimension,
    keys: string[],
  ) =>
    typedError<UsageGroup[], string>(
      __TAURI_INVOKE('query_traffic_usage_by_keys', { query, groupBy, keys }),
    ),
  queryTrafficClosedConnections: (
    range: TrafficRange,
    filters: TrafficFilter[],
    before: {
      closed_at: number;
      id: string;
    } | null,
    limit: number,
  ) =>
    typedError<ClosedPage, string>(
      __TAURI_INVOKE('query_traffic_closed_connections', {
        range,
        filters,
        before,
        limit,
      }),
    ),
  queryTrafficActiveConnectionIds: (filters: TrafficFilter[]) =>
    typedError<string[], string>(
      __TAURI_INVOKE('query_traffic_active_connection_ids', { filters }),
    ),
  getClashWsConnectionsState: () =>
    typedError<ClashConnectionsConnectorState, string>(
      __TAURI_INVOKE('get_clash_ws_connections_state'),
    ),
  getClashWsSnapshot: () =>
    typedError<ClashWsSnapshot, string>(
      __TAURI_INVOKE('get_clash_ws_snapshot'),
    ),
  setClashWsRecording: (kind: ClashWsKind, enabled: boolean) =>
    typedError<ClashWsRecording, string>(
      __TAURI_INVOKE('set_clash_ws_recording', { kind, enabled }),
    ),
  clearClashWsHistory: (kind: ClashWsKind) =>
    typedError<null, string>(
      __TAURI_INVOKE('clear_clash_ws_history', { kind }),
    ),
  checkUpdate: () =>
    typedError<
      {
        rid: number;
        available: boolean;
        current_version: string;
        version: string;
        date: string | null;
        body: string | null;
        raw_json: any;
      } | null,
      string
    >(__TAURI_INVOKE('check_update')),
  isPortable: () => typedError<boolean, string>(__TAURI_INVOKE('is_portable')),
  isAppimage: () => typedError<boolean, string>(__TAURI_INVOKE('is_appimage')),
  openThat: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE('open_that', { path })),
  cleanupProcesses: () =>
    typedError<null, string>(__TAURI_INVOKE('cleanup_processes')),
  getServerPort: () =>
    typedError<number, string>(__TAURI_INVOKE('get_server_port')),
  getCoreDir: () => typedError<string, string>(__TAURI_INVOKE('get_core_dir')),
  getServiceInstallPrompt: () =>
    typedError<string, string>(__TAURI_INVOKE('get_service_install_prompt')),
  openAppConfigDir: () =>
    typedError<null, string>(__TAURI_INVOKE('open_app_config_dir')),
  openAppDataDir: () =>
    typedError<null, string>(__TAURI_INVOKE('open_app_data_dir')),
  openCoreDir: () => typedError<null, string>(__TAURI_INVOKE('open_core_dir')),
  openLogsDir: () => typedError<null, string>(__TAURI_INVOKE('open_logs_dir')),
  getCoreVersion: (coreType: ClashCore_Deserialize) =>
    typedError<string, string>(
      __TAURI_INVOKE('get_core_version', { coreType }),
    ),
  updateCore: (coreType: ClashCore_Deserialize) =>
    typedError<number, string>(__TAURI_INVOKE('update_core', { coreType })),
  /**  restart the sidecar */
  restartSidecar: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_sidecar')),
  fetchLatestCoreVersions: () =>
    typedError<ManifestVersionLatest, string>(
      __TAURI_INVOKE('fetch_latest_core_versions'),
    ),
  inspectUpdater: (updaterId: number) =>
    typedError<UpdaterSummary, string>(
      __TAURI_INVOKE('inspect_updater', { updaterId }),
    ),
  getStorageItem: (key: string) =>
    typedError<string | null, string>(
      __TAURI_INVOKE('get_storage_item', { key }),
    ),
  setStorageItem: (key: string, value: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('set_storage_item', { key, value }),
    ),
  removeStorageItem: (key: string) =>
    typedError<null, string>(__TAURI_INVOKE('remove_storage_item', { key })),
  /**
   *  Debug: returns all frontend KV entries (keys with the `web:` prefix).
   *  Internal storage entries used by other subsystems are excluded.
   */
  getAllStorageItems: () =>
    typedError<StorageEntry[], string>(__TAURI_INVOKE('get_all_storage_items')),
  getHotkeys: () => typedError<string[], string>(__TAURI_INVOKE('get_hotkeys')),
  setHotkeys: (hotkeys: string[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('set_hotkeys', { hotkeys }),
    ),
  /**
   *  Debug: clears all frontend KV entries (keys with the `web:` prefix).
   *  Internal storage entries used by other subsystems are left intact.
   */
  clearStorage: () => typedError<null, string>(__TAURI_INVOKE('clear_storage')),
  statusService: () =>
    typedError<ServiceStatusInfo_Serialize, string>(
      __TAURI_INVOKE('status_service'),
    ),
  installService: () =>
    typedError<null, string>(__TAURI_INVOKE('install_service')),
  uninstallService: () =>
    typedError<null, string>(__TAURI_INVOKE('uninstall_service')),
  startService: () => typedError<null, string>(__TAURI_INVOKE('start_service')),
  stopService: () => typedError<null, string>(__TAURI_INVOKE('stop_service')),
  restartService: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_service')),
  saveWindowSizeState: (label: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_window_size_state', { label }),
    ),
  createMainWindow: () =>
    typedError<null, string>(__TAURI_INVOKE('create_main_window')),
  createLegacyWindow: () =>
    typedError<null, string>(__TAURI_INVOKE('create_legacy_window')),
  agentGetManifest: () => __TAURI_INVOKE<AgentManifest>('agent_get_manifest'),
  agentExecuteTool: (request: AgentToolRequest) =>
    typedError<AgentToolResult, string>(
      __TAURI_INVOKE('agent_execute_tool', { request }),
    ),
  agentExecuteReadonlyTool: (tool: AgentToolName) =>
    typedError<AgentToolResult, string>(
      __TAURI_INVOKE('agent_execute_readonly_tool', { tool }),
    ),
  agentProbeNetwork: (request: AgentNetworkProbeRequest) =>
    typedError<AgentNetworkProbeResult, string>(
      __TAURI_INVOKE('agent_probe_network', { request }),
    ),
  agentResolveIntent: (request: AgentIntentRequest) =>
    __TAURI_INVOKE<AgentIntentResolution>('agent_resolve_intent', { request }),
  agentGetNetworkSnapshot: () =>
    __TAURI_INVOKE<AgentNetworkSnapshot>('agent_get_network_snapshot'),
  agentProposeNetworkAction: (action: AgentActionRequest) =>
    typedError<AgentProposal, string>(
      __TAURI_INVOKE('agent_propose_network_action', { action }),
    ),
  agentExecuteNetworkAction: (proposalId: string, digest: string) =>
    typedError<AgentActionResult, string>(
      __TAURI_INVOKE('agent_execute_network_action', { proposalId, digest }),
    ),
  agentCancelNetworkAction: (proposalId: string) =>
    typedError<boolean, string>(
      __TAURI_INVOKE('agent_cancel_network_action', { proposalId }),
    ),
};

/** Events */
export const events = {
  clashConnectionsEvent: makeEvent<ClashConnectionsEvent>(
    'clash-connections-event',
  ),
  clashWsEvent: makeEvent<ClashWsEvent>('clash-ws-event'),
  storageValueChangedEvent: makeEvent<StorageValueChangedEvent>(
    'storage-value-changed-event',
  ),
};

/* Types */
export type AgentActionKind =
  | 'set_routing_mode'
  | 'set_tun_enabled'
  | 'set_system_proxy_enabled'
  | 'disable_stale_system_proxy';

export type AgentActionRequest =
  | { action: 'set_routing_mode'; mode: AgentRoutingMode }
  | { action: 'set_tun_enabled'; enabled: boolean }
  | { action: 'set_system_proxy_enabled'; enabled: boolean }
  | { action: 'disable_stale_system_proxy' };

export type AgentActionResult = {
  proposal_id: string;
  action: AgentActionKind;
  verified: boolean;
  snapshot: AgentNetworkSnapshot;
};

export type AgentActionRisk = 'traffic_change' | 'host_network_change';

export type AgentAppliedState = 'consistent' | 'stale' | 'unknown';

export type AgentConnectorState =
  'disconnected' | 'connecting' | 'connected' | 'unknown';

export type AgentCoreSnapshot = {
  state: AgentCoreState;
  run_type: AgentRunType;
  selected_core: string;
  state_changed_at: number;
  runtime_config_present: boolean;
  routing_mode: AgentRoutingMode | null;
  observed_routing_mode: AgentRoutingMode | null;
  applied_consistency: AgentAppliedState;
};

export type AgentCoreState = 'running' | 'stopped' | 'unknown';

export type AgentDiagnosticSummary = {
  revision: string;
  captured_at: number;
  health: AgentHealth;
  findings: AgentFinding[];
  probe_failures: AgentProbeFailure[];
  privacy: AgentPrivacyBoundary;
};

export type AgentFinding = {
  code: AgentFindingCode;
  severity: AgentFindingSeverity;
  recommended_action: AgentActionRequest | null;
};

export type AgentFindingCode =
  | 'weak_controller_secret'
  | 'system_proxy_without_running_core'
  | 'system_proxy_endpoint_mismatch'
  | 'runtime_config_missing'
  | 'active_profile_missing'
  | 'service_mode_inconsistent'
  | 'clash_connector_disconnected'
  | 'tun_runtime_mismatch'
  | 'recent_core_errors';

export type AgentFindingSeverity = 'info' | 'warning' | 'critical';

export type AgentHealth = 'healthy' | 'warning' | 'critical' | 'degraded';

export type AgentHostScope = 'loopback' | 'non_loopback' | 'unknown';

export type AgentImpact =
  | 'existing_connections_may_change'
  | 'traffic_may_bypass_proxy'
  | 'all_traffic_uses_proxy'
  | 'restore_rule_routing'
  | 'host_system_proxy_enabled'
  | 'host_system_proxy_disabled'
  | 'host_tun_enabled'
  | 'host_tun_disabled';

export type AgentIntent =
  | { intent: 'diagnose' }
  | { intent: 'set_routing_mode'; mode: AgentRoutingMode }
  | { intent: 'set_tun_enabled'; enabled: boolean }
  | { intent: 'set_system_proxy_enabled'; enabled: boolean }
  | { intent: 'disable_stale_system_proxy' };

export type AgentIntentRequest = {
  text: string;
};

export type AgentIntentResolution =
  | { status: 'resolved'; intent: AgentIntent }
  | { status: 'unsupported'; reason: AgentUnsupportedIntentReason };

export type AgentManifest = {
  schema_version: number;
  tools: AgentToolManifest[];
};

export type AgentNetworkProbeRequest = {
  url: string;
  expected_status: number | null;
  timeout_ms: number | null;
};

export type AgentNetworkProbeResult = {
  status: number;
  expected_status: number | null;
  matches_expected_status: boolean | null;
  latency_ms: number;
};

export type AgentNetworkSnapshot = {
  schema_version: number;
  revision: string;
  captured_at: number;
  app_version: string;
  os_family: string;
  health: AgentHealth;
  core: AgentCoreSnapshot;
  service: AgentServiceSnapshot;
  system_proxy: AgentSystemProxySnapshot;
  tun: AgentTunSnapshot;
  profiles: AgentProfileSnapshot;
  telemetry: AgentTelemetrySnapshot;
  findings: AgentFinding[];
  probe_failures: AgentProbeFailure[];
  privacy: AgentPrivacyBoundary;
};

export type AgentPrivacyBoundary = {
  contains_raw_logs: boolean;
  contains_profile_names: boolean;
  contains_profile_urls: boolean;
  contains_connection_targets: boolean;
  contains_controller_secret: boolean;
};

export type AgentProbeCode =
  | 'core_status_unavailable'
  | 'core_config_unavailable'
  | 'profiles_unavailable'
  | 'system_proxy_unavailable'
  | 'service_status_unavailable'
  | 'telemetry_unavailable';

export type AgentProbeFailure = {
  code: AgentProbeCode;
};

export type AgentProfileSnapshot = {
  total_count: number;
  active_count: number;
  remote_count: number;
  local_count: number;
  active_references_valid: boolean;
};

export type AgentProposal = {
  id: string;
  digest: string;
  action: AgentActionRequest;
  risk: AgentActionRisk;
  impacts: AgentImpact[];
  changes: AgentStateChange[];
  snapshot_revision: string;
  created_at: number;
  expires_at: number;
  requires_confirmation: boolean;
};

export type AgentRoutingMode = 'rule' | 'global' | 'direct';

export type AgentRunType = 'normal' | 'service' | 'elevated';

export type AgentServiceSnapshot = {
  desired_enabled: boolean;
  state: AgentServiceState;
  ipc_connected: boolean;
  runtime_compatible: boolean | null;
};

export type AgentServiceState =
  'not_installed' | 'stopped' | 'running' | 'unknown';

export type AgentStateChange = {
  field: string;
  before: string;
  after: string;
};

export type AgentSystemProxySnapshot = {
  desired_enabled: boolean;
  observed_enabled: boolean | null;
  observed_host_scope: AgentHostScope;
  observed_port: number | null;
  expected_mixed_port: number;
  matches_expected_endpoint: boolean | null;
};

export type AgentTelemetrySnapshot = {
  state: AgentConnectorState;
  active_connection_count: number | null;
  upload_speed: number | null;
  download_speed: number | null;
  upload_total: string | null;
  download_total: string | null;
  recent_error_count: number;
};

export type AgentToolManifest = {
  name: AgentToolName;
  version: number;
  description: string;
  risk: AgentToolRisk;
  read_only: boolean;
  timeout_ms: number;
  input_schema_version: number;
  output_schema_version: number;
};

export type AgentToolName =
  | 'system.snapshot'
  | 'network.diagnose'
  | 'network.probe'
  | 'core.status'
  | 'proxy.status'
  | 'tun.status'
  | 'profile.summary'
  | 'service.status';

export type AgentToolRequest =
  | { tool: 'system.snapshot' }
  | { tool: 'network.diagnose' }
  | { tool: 'network.probe'; arguments: AgentNetworkProbeRequest }
  | { tool: 'core.status' }
  | { tool: 'proxy.status' }
  | { tool: 'tun.status' }
  | { tool: 'profile.summary' }
  | { tool: 'service.status' };

export type AgentToolResult =
  | { tool: 'system.snapshot'; output: AgentNetworkSnapshot }
  | { tool: 'network.diagnose'; output: AgentDiagnosticSummary }
  | { tool: 'network.probe'; output: AgentNetworkProbeResult }
  | { tool: 'core.status'; output: AgentCoreSnapshot }
  | { tool: 'proxy.status'; output: AgentSystemProxySnapshot }
  | { tool: 'tun.status'; output: AgentTunSnapshot }
  | { tool: 'profile.summary'; output: AgentProfileSnapshot }
  | { tool: 'service.status'; output: AgentServiceSnapshot };

export type AgentToolRisk = 'read_only';

export type AgentTunSnapshot = {
  desired_enabled: boolean;
  generated_runtime_enabled: boolean | null;
  observed_active: AgentAppliedState;
  applied_consistency: AgentAppliedState;
};

export type AgentUnsupportedIntentReason =
  'empty_input' | 'input_too_long' | 'no_matching_intent';

export type BreakWhenProxyChange = 'none' | 'chain' | 'all';

export type BuildInfo = {
  app_name: string;
  app_version: string;
  pkg_version: string;
  commit_hash: string;
  commit_author: string;
  commit_date: string;
  build_date: string;
  build_profile: string;
  build_platform: string;
  rustc_version: string;
  llvm_version: string;
};

/**  Built-in post-processing steps applied to the selected config. */
export type BuiltinStepKind =
  'guard_overrides' | 'whitelist_field_filter' | 'finalizing';

export type Bytes = {
  upload: number;
  download: number;
};

export type ClashConnectionsConnectorEvent =
  | { kind: 'state_changed'; data: ClashConnectionsConnectorState }
  | { kind: 'update'; data: ClashConnectionsInfo };

export type ClashConnectionsConnectorState =
  'disconnected' | 'connecting' | 'connected';

export type ClashConnectionsEvent = ClashConnectionsConnectorEvent;

export type ClashConnectionsInfo = {
  downloadTotal: number;
  uploadTotal: number;
  downloadSpeed: number;
  uploadSpeed: number;
};

export type ClashCore = ClashCore_Serialize | ClashCore_Deserialize;

export type ClashCoreType =
  | 'mihomo'
  | 'mihomo-alpha'
  | 'clash-rs'
  | 'clash-rs-alpha'
  | 'clash'
  | 'chimera_client';

export type ClashCore_Deserialize =
  | 'clash'
  | 'clash-premium'
  | 'clash-rs'
  | 'mihomo'
  | 'clash-meta'
  | 'chimera-client'
  | 'chimera'
  | 'chimera_client'
  | 'mihomo-alpha'
  | 'clash-rs-alpha';

export type ClashCore_Serialize =
  | 'clash'
  | 'clash-rs'
  | 'mihomo'
  | 'chimera-client'
  | 'mihomo-alpha'
  | 'clash-rs-alpha';

export type ClashInfo = {
  /**  clash core port */
  port: number;
  /**  same as `external-controller` */
  server: string;
  /**  clash secret */
  secret: string | null;
};

/**  Runtime state returned by the running core's `GET /configs` endpoint. */
export type ClashRuntimeConfig = {
  port: number | null;
  mode: string | null;
  ipv6: boolean | null;
  'socket-port': number | null;
  'allow-lan': boolean | null;
  'log-level': string | null;
  'mixed-port': number | null;
  'redir-port': number | null;
  'socks-port': number | null;
  'tproxy-port': number | null;
  'external-controller': string | null;
  secret: string | null;
};

export type ClashStrategy = {
  external_controller_port_strategy: ExternalControllerPortStrategy;
};

export type ClashWsConnectionSnapshot = {
  downloadTotal: number;
  uploadTotal: number;
  downloadSpeed: number;
  uploadSpeed: number;
  memory: number | null;
  connections: any | null;
};

export type ClashWsEvent =
  | { kind: 'state_changed'; data: ClashConnectionsConnectorState }
  | { kind: 'connections_updated'; data: ClashWsConnectionSnapshot }
  | { kind: 'log_appended'; data: ClashWsLog }
  | { kind: 'traffic_updated'; data: ClashWsTraffic }
  | { kind: 'memory_updated'; data: ClashWsMemory }
  | { kind: 'recording_changed'; data: ClashWsRecording }
  | { kind: 'history_cleared'; data: ClashWsKind };

export type ClashWsKind = 'connections' | 'logs' | 'traffic' | 'memory';

export type ClashWsLog = {
  type: string;
  time: string | null;
  payload: string;
};

export type ClashWsMemory = {
  inuse: number;
  oslimit: number;
};

export type ClashWsRecording = {
  connections: boolean;
  logs: boolean;
  traffic: boolean;
  memory: boolean;
};

export type ClashWsSnapshot = {
  state: ClashConnectionsConnectorState;
  recording: ClashWsRecording;
  connections: ClashWsConnectionSnapshot[];
  logs: ClashWsLog[];
  traffic: ClashWsTraffic[];
  memory: ClashWsMemory[];
};

export type ClashWsTraffic = {
  up: number;
  down: number;
};

export type ClosedConnection = {
  id: string;
  started_at: number;
  first_seen_at: number;
  closed_at: number;
  bytes: Bytes;
  dimensions: Dimensions;
};

/**  Exclusive position for newest-first paging. */
export type ClosedCursor = {
  closed_at: number;
  id: string;
};

export type ClosedPage = {
  connections: ClosedConnection[];
  next: ClosedCursor | null;
};

/**  A source commit and its critical runtime result. Peripheral owners settle separately. */
export type CommitReceipt = {
  operation_id: string | null;
  domain: string;
  source_version: number;
  runtime: RuntimeCommitStatus;
};

/**  A profile that can produce a complete config and can be selected by current. */
export type ConfigDefinition =
  ConfigDefinition_Serialize | ConfigDefinition_Deserialize;

/**  A profile that can produce a complete config and can be selected by current. */
export type ConfigDefinition_Deserialize =
  /**  A config parsed from a locally materialized file. */
  | ({
      type: 'file';
      source: ProfileSource_Deserialize;
      transforms?: ProfileId[];
    } & { base?: never; extend_proxies_from?: never })
  /**  A config composed from an optional full base and proxy contributors. */
  | ({
      type: 'composition';
      base?: ProfileId | null;
      extend_proxies_from?: ProfileId[];
      transforms?: ProfileId[];
    } & { source?: never });

/**  A profile that can produce a complete config and can be selected by current. */
export type ConfigDefinition_Serialize =
  /**  A config parsed from a locally materialized file. */
  | ({
      type: 'file';
      source: ProfileSource_Serialize;
      transforms?: ProfileId[];
    } & { base?: never; extend_proxies_from?: never })
  /**  A config composed from an optional full base and proxy contributors. */
  | ({
      type: 'composition';
      base?: ProfileId | null;
      extend_proxies_from?: ProfileId[];
      transforms?: ProfileId[];
    } & { source?: never });

/**  Why a config pipeline is being executed. */
export type ConfigExecutionRole =
  /**  The final config selected by `Profiles.current`. */
  | { kind: 'selected' }
  /**  Built as the base member of a composition. */
  | {
      kind: 'composition_base';
      data: {
        composition_id: ProfileId;
      };
    }
  /**  Built as a proxies contributor of a composition. */
  | {
      kind: 'composition_contributor';
      data: {
        composition_id: ProfileId;
        contributor_index: number;
      };
    };

export type ConfigRevisionInfo = {
  epoch: number;
  generation: number;
  source_hash: string;
  effective_hash: string;
};

/**  The active core's controller endpoint without its private credential. */
export type CoreControllerInfo =
  | ({ NamedPipe: string } & { Http?: never; UnixSocket?: never })
  | ({ UnixSocket: string } & { Http?: never; NamedPipe?: never })
  | ({ Http: string } & { NamedPipe?: never; UnixSocket?: never });

export type CoreHealthInfo = {
  state: CoreHealthState;
  changed_at: number;
  consecutive_failures: number;
  last_error: string | null;
  last_success_at: number | null;
};

export type CoreHealthState = 'Starting' | 'Healthy' | 'Unhealthy';

export type CoreInfos = CoreInfos_Serialize | CoreInfos_Deserialize;

export type CoreInfos_Deserialize = {
  instance_id?: string | null;
  type: CoreType | null;
  state: CoreState;
  state_changed_at: number;
  config_path: string | null;
  controller?: CoreControllerInfo | null;
  health?: CoreHealthInfo | null;
  revision?: ConfigRevisionInfo | null;
  detail?: CoreStateDetail | null;
};

export type CoreInfos_Serialize = {
  instance_id?: string | null;
  type: CoreType | null;
  state: CoreState;
  state_changed_at: number;
  config_path: string | null;
  controller?: CoreControllerInfo | null;
  health?: CoreHealthInfo | null;
  revision?: ConfigRevisionInfo | null;
  detail?: CoreStateDetail | null;
};

export type CoreLifecycleOperationResult = {
  id: number;
  error: string | null;
};

export type CoreLifecycleStatus = {
  active: number | null;
  queued: number[];
  uncertain: boolean;
  shutting_down: boolean;
  completed: CoreLifecycleOperationResult[];
};

export type CoreState = 'Running' | { Stopped: string | null };

export type CoreStateDetail =
  | ({
      Stopped: {
        reason: string | null;
      };
    } & {
      Restarting?: never;
      Running?: never;
      Starting?: never;
      Stopping?: never;
      Switching?: never;
    })
  | ({
      Starting: {
        epoch: number;
      };
    } & {
      Restarting?: never;
      Running?: never;
      Stopped?: never;
      Stopping?: never;
      Switching?: never;
    })
  | ({
      Running: {
        epoch: number;
        pid: number;
      };
    } & {
      Restarting?: never;
      Starting?: never;
      Stopped?: never;
      Stopping?: never;
      Switching?: never;
    })
  | ({
      Restarting: {
        epoch: number;
        attempt: number;
      };
    } & {
      Running?: never;
      Starting?: never;
      Stopped?: never;
      Stopping?: never;
      Switching?: never;
    })
  | ({
      Switching: {
        from: number | null;
        to: number;
      };
    } & {
      Restarting?: never;
      Running?: never;
      Starting?: never;
      Stopped?: never;
      Stopping?: never;
    })
  | ({
      Stopping: {
        epoch: number;
      };
    } & {
      Restarting?: never;
      Running?: never;
      Starting?: never;
      Stopped?: never;
      Switching?: never;
    });

export type CoreType = { clash: ClashCoreType } | 'singbox';

export type Degradation = {
  phase: DegradationPhase;
  code: string;
  message: string;
  retryable: boolean;
};

export type DegradationPhase =
  | 'legacy_mirror'
  | 'profile_materialization'
  | 'runtime_build'
  | 'runtime_check'
  | 'runtime_promote'
  | 'runtime_publish'
  | 'runtime_apply'
  | 'core_rollback'
  | 'system_effect'
  | 'ui_effect';

export type DelayRes = {
  delay: number;
};

export type DeviceInfo = {
  cpu: string[];
  memory: string;
};

/**  A way to slice usage: ranking, filtering and topology layers all name dimensions. */
export type Dimension =
  /**  Derived: the process when known, else the source. */
  | 'origin'
  | 'process'
  | 'source'
  | 'inbound'
  | 'target'
  | 'protocol'
  | 'rule'
  /**  The strategy groups without the exit, outermost first; empty without groups. */
  | 'chain'
  | 'exit'
  | 'profile'
  | 'source_region'
  | 'destination_region'
  /**  How the destination region was located; empty while it is unknown. */
  | 'destination_basis';

export type Dimensions = {
  /**  Process path or name. */
  process: string;
  source: string;
  /**  `inbound_user`, else `inbound_name`. */
  inbound?: string;
  /**  Host, else destination IP. */
  target: string;
  protocol: string;
  rule: RuleKey;
  /**  Clash wire order: exit first, outermost group last. */
  chains: string[];
  /**  The profile that was current when the connection first appeared; never rewritten. */
  profile?: string | null;
  /**  An upper-case country code, or `unknown`. */
  source_region?: string;
  destination_region?: string;
  /**  How `destination_region` was located; `None` while it is unknown. */
  destination_basis?: GeoBasis | null;
};

/**  A snapshot of a download session's progress, polled by IPC. */
export type DownloadStatus = {
  state: DownloaderState;
  downloaded: number;
  total: number;
  speed: number | null;
};

/**  The high-level state of a download session. */
export type DownloaderState =
  'idle' | 'downloading' | { failed: string } | 'finished';

export type EditorWindowType = 'profile' | 'css-editor';

export type EnvInfo = {
  os: string;
  arch: string;
  core: { [key in string]: string };
  device: DeviceInfo;
  build_info: BuildInfo;
};

export type ExternalControllerPortStrategy =
  'fixed' | 'random' | 'allow_fallback';

export type ExternalMode = 'symlink' | 'mirror';

/**  An absolute path outside the managed profile directory. */
export type ExternalProfilePath = string;

/**  What the address a destination was located by is to the outbound. */
export type GeoBasis =
  /**  The outbound dialed this address. */
  | 'dialed'
  /**  The outbound was handed the host; the core resolved this address only for its rules. */
  | 'resolved';

export type GetSysProxyResponse = {
  enable: boolean;
  host: string;
  port: number;
  bypass: string;
  server: string;
};

export type IVerge = IVerge_Serialize | IVerge_Deserialize;

export type IVerge_Deserialize =
  | ({
      /**  1. 日记轮转时间，单位：天 */
      max_log_files: number | null;
      /**
       *  2. app log level
       *  silent | error | warn | info | debug | trace
       */
      app_log_level: LoggingLevel_Deserialize | null;
      /**  3. theme setting */
      theme_color: string | null;
      /**  4. clash tun mode */
      enable_tun_mode: boolean | null;
      /**  5. set system proxy */
      enable_system_proxy: boolean | null;
      /**  5.1. auto launch on system startup */
      enable_auto_launch: boolean | null;
      /**  5.2. do not show window when app launches */
      enable_silent_start: boolean | null;
      /**  6. windows service mode */
      enable_service_mode: boolean | null;
      /**  6.1. window always on top */
      always_on_top: boolean | null;
      /**
       *  6.2. legacy window size and position tuple
       * @deprecated use `window_size_state` instead
       */
      window_size_position: (number | null)[] | null;
      /**  6.3. window size and position */
      window_size_state: WindowState | null;
      /**  6.3. global ui framer motion effects */
      lighten_animation_effects: boolean | null;
      /**  7. 是否使用内部的脚本支持，默认为真 */
      enable_builtin_enhanced: boolean | null;
      /**  8. clash core path */
      clash_core: ClashCore_Deserialize | null;
      /**  9. 支持关闭字段过滤，避免meta的新字段都被过滤掉，默认为真 */
      enable_clash_fields: boolean | null;
      /**  10. Clash 相关策略 */
      clash_strategy: ClashStrategy | null;
      /**  11. set system proxy bypass */
      system_proxy_bypass: string | null;
      /**  11.1. web ui list */
      web_ui_list: string[] | null;
      /**  12. verge mixed port 用于覆盖 clash 的 mixed port */
      verge_mixed_port: number | null;
      /**  23. use a random mixed port on startup */
      enable_random_port: boolean | null;
      /**  13. enable proxy guard */
      enable_proxy_guard: boolean | null;
      /**  15. Check update when app launch */
      enable_auto_check_update: boolean | null;
      /**  How long recorded connection traffic is kept. */
      traffic_retention: TrafficRetention | null;
      /**
       *  16. 切换代理时中断连接
       *  None: 不中断
       *  Chain: 仅中断使用该代理链的连接
       *  All: 中断所有连接
       */
      break_when_proxy_change: BreakWhenProxyChange | null;
      /**
       *  17. 切换配置时中断连接
       *  true: 中断所有连接
       *  false: 不中断连接
       */
      break_when_profile_change: boolean | null;
      /**
       *  18. 切换模式时中断连接
       *  true: 中断所有连接
       *  false: 不中断连接
       */
      break_when_mode_change: boolean | null;
      /**  19. `light` or `dark` or `system` */
      theme_mode: string | null;
      /**  20. i18n */
      language: string | null;
      /**
       *  21. Legacy compatibility field for older configs.
       *  Prefer window_type for new code.
       */
      use_legacy_ui: boolean | null;
      /**
       *  22. Tun 堆栈选择
       *  TODO: 弃用此字段，转移到 clash config 里
       */
      tun_stack: TunStack | null;
      /**  23. show proxies in tray menu */
      clash_tray_selector: ProxiesSelectorMode | null;
      /**
       *  24. Window type to use when opening the app window
       *  Main: opens new main window
       *  Legacy: opens legacy window
       */
      window_type: WindowType | null;
    } & {
      /**  14. proxy guard interval */
      proxy_guard_interval: number | null;
    })
  | {
      /**  14. proxy guard interval */
      proxy_guard_duration: number | null;
    };

export type IVerge_Serialize = {
  /**  1. 日记轮转时间，单位：天 */
  max_log_files: number | null;
  /**
   *  2. app log level
   *  silent | error | warn | info | debug | trace
   */
  app_log_level: LoggingLevel_Serialize | null;
  /**  3. theme setting */
  theme_color: string | null;
  /**  4. clash tun mode */
  enable_tun_mode: boolean | null;
  /**  5. set system proxy */
  enable_system_proxy: boolean | null;
  /**  5.1. auto launch on system startup */
  enable_auto_launch: boolean | null;
  /**  5.2. do not show window when app launches */
  enable_silent_start: boolean | null;
  /**  6. windows service mode */
  enable_service_mode?: boolean | null;
  /**  6.1. window always on top */
  always_on_top?: boolean | null;
  /**
   *  6.2. legacy window size and position tuple
   * @deprecated use `window_size_state` instead
   */
  window_size_position?: (number | null)[] | null;
  /**  6.3. window size and position */
  window_size_state?: WindowState | null;
  /**  6.3. global ui framer motion effects */
  lighten_animation_effects: boolean | null;
  /**  7. 是否使用内部的脚本支持，默认为真 */
  enable_builtin_enhanced: boolean | null;
  /**  8. clash core path */
  clash_core?: ClashCore_Serialize | null;
  /**  9. 支持关闭字段过滤，避免meta的新字段都被过滤掉，默认为真 */
  enable_clash_fields: boolean | null;
  /**  10. Clash 相关策略 */
  clash_strategy: ClashStrategy | null;
  /**  11. set system proxy bypass */
  system_proxy_bypass: string | null;
  /**  11.1. web ui list */
  web_ui_list: string[] | null;
  /**  12. verge mixed port 用于覆盖 clash 的 mixed port */
  verge_mixed_port: number | null;
  /**  23. use a random mixed port on startup */
  enable_random_port: boolean | null;
  /**  13. enable proxy guard */
  enable_proxy_guard: boolean | null;
  /**  14. proxy guard interval */
  proxy_guard_interval: number | null;
  /**  15. Check update when app launch */
  enable_auto_check_update: boolean | null;
  /**  How long recorded connection traffic is kept. */
  traffic_retention: TrafficRetention | null;
  /**
   *  16. 切换代理时中断连接
   *  None: 不中断
   *  Chain: 仅中断使用该代理链的连接
   *  All: 中断所有连接
   */
  break_when_proxy_change: BreakWhenProxyChange | null;
  /**
   *  17. 切换配置时中断连接
   *  true: 中断所有连接
   *  false: 不中断连接
   */
  break_when_profile_change: boolean | null;
  /**
   *  18. 切换模式时中断连接
   *  true: 中断所有连接
   *  false: 不中断连接
   */
  break_when_mode_change: boolean | null;
  /**  19. `light` or `dark` or `system` */
  theme_mode: string | null;
  /**  20. i18n */
  language: string | null;
  /**
   *  21. Legacy compatibility field for older configs.
   *  Prefer window_type for new code.
   */
  use_legacy_ui: boolean | null;
  /**
   *  22. Tun 堆栈选择
   *  TODO: 弃用此字段，转移到 clash config 里
   */
  tun_stack: TunStack | null;
  /**  23. show proxies in tray menu */
  clash_tray_selector: ProxiesSelectorMode | null;
  /**
   *  24. Window type to use when opening the app window
   *  Main: opens new main window
   *  Legacy: opens legacy window
   */
  window_type: WindowType | null;
};

export type IpsbResponse = {
  organization: string;
  longitude: number | null;
  timezone: string;
  isp: string;
  offset: number;
  asn: number;
  asn_organization: string;
  country: string;
  ip: string;
  latitude: number | null;
  continent_code: string;
  country_code: string;
};

export type LocalBinding = LocalBinding_Serialize | LocalBinding_Deserialize;

export type LocalBinding_Deserialize =
  | ({
      type: 'managed';
      file: ManagedProfilePath;
      updated_at?: number | null;
    } & { mode?: never; target?: never })
  | {
      type: 'external';
      file: ManagedProfilePath;
      updated_at?: number | null;
      target: ExternalProfilePath;
      mode: ExternalMode;
    };

export type LocalBinding_Serialize =
  | ({
      type: 'managed';
      file: ManagedProfilePath;
      updated_at?: number | null;
    } & { mode?: never; target?: never })
  | {
      type: 'external';
      file: ManagedProfilePath;
      updated_at?: number | null;
      target: ExternalProfilePath;
      mode: ExternalMode;
    };

export type LogSpan = 'log' | 'info' | 'warn' | 'error';

export type LoggingLevel = LoggingLevel_Serialize | LoggingLevel_Deserialize;

export type LoggingLevel_Deserialize =
  | 'silent'
  | 'off'
  | 'trace'
  | 'tracing'
  | 'debug'
  | 'info'
  | 'warn'
  | 'warning'
  | 'error';

export type LoggingLevel_Serialize =
  'silent' | 'trace' | 'debug' | 'info' | 'warn' | 'error';

/**  A path relative to the application-managed profile directory. */
export type ManagedProfilePath = string;

export type ManifestVersionLatest = {
  mihomo: string;
  mihomo_alpha: string;
  clash_rs: string;
  chimera_client: string;
  clash_rs_alpha: string;
  clash_premium: string;
};

/**  What a topology orders and merges its nodes by. */
export type Metric = 'bytes' | 'connections';

/**
 *  Public mutation wire aligned with REF: desired state is committed first;
 *  post-commit side-effect failures degrade instead of turning the mutation
 *  into an error that would imply the commit was rolled back.
 */
export type MutationOutcome<T> =
  | {
      status: 'committed';
      value: T;
      commits: CommitReceipt[];
      notifications_pending: boolean;
    }
  | {
      status: 'committed_degraded';
      value: T;
      commits: CommitReceipt[];
      notifications_pending: boolean;
      degradations: Degradation[];
    };

export type NetworkProbeRequest = {
  url: string;
  expected_status: number | null;
  timeout_ms: number | null;
};

export type NetworkProbeResult = {
  status: number;
  expected_status: number | null;
  matches_expected_status: boolean | null;
  latency_ms: number;
};

export type NewProfileRequest =
  NewProfileRequest_Serialize | NewProfileRequest_Deserialize;

export type NewProfileRequest_Deserialize = {
  metadata: ProfileMetadata_Deserialize;
  /**  Add rewrites the materialized path to `{uid}.{ext}`. */
  definition: ProfileDefinition_Deserialize;
};

export type NewProfileRequest_Serialize = {
  metadata: ProfileMetadata_Serialize;
  /**  Add rewrites the materialized path to `{uid}.{ext}`. */
  definition: ProfileDefinition_Serialize;
};

/**  The pipeline operator that produced a snapshot node. */
export type OperatorTag =
  | {
      kind: 'file_config_root';
      data: {
        profile_id: ProfileId;
        role: ConfigExecutionRole;
      };
    }
  /**  `base: None` is the clean seed (`proxies: []`). */
  | {
      kind: 'composition_root';
      data: {
        profile_id: ProfileId;
        base: ProfileId | null;
      };
    }
  | {
      kind: 'extend_proxies_step';
      data: {
        composition_id: ProfileId;
        contributor_profile_id: ProfileId;
        contributor_index: number;
      };
    }
  | {
      kind: 'scoped_transform';
      data: {
        host_profile_id: ProfileId;
        role: ConfigExecutionRole;
        transform_profile_id: ProfileId;
        transform_kind: TransformKind;
        step_index: number;
      };
    }
  /**  `selected_profile_id: None` = bare 模式（current 为空，spec §2 目标 6）。 */
  | {
      kind: 'global_transform';
      data: {
        selected_profile_id: ProfileId | null;
        transform_profile_id: ProfileId;
        transform_kind: TransformKind;
        step_index: number;
      };
    }
  | {
      kind: 'builtin_step';
      data: {
        selected_profile_id: ProfileId | null;
        step: BuiltinStepKind;
      };
    }
  /**  current = None 的裸配置管线根（spec §8.2）。 */
  | { kind: 'bare_root' }
  /**  内建增强脚本步骤；`name` 为展示性字段，`node_key()` 丢弃。 */
  | {
      kind: 'builtin_transform';
      data: {
        selected_profile_id: ProfileId | null;
        name: string;
        step_index: number;
      };
    };

export type PatchClashCoreConfig =
  PatchClashCoreConfig_Serialize | PatchClashCoreConfig_Deserialize;

export type PatchClashCoreConfig_Deserialize = {
  'mixed-port'?: number | null;
  secret?: string | null;
  'external-controller'?: string | null;
};

export type PatchClashCoreConfig_Serialize = {
  'mixed-port'?: number | null;
  secret?: string | null;
  'external-controller'?: string | null;
};

/**  Typed IPC payload for modifying persistent runtime overrides. */
export type PatchRuntimeConfig =
  PatchRuntimeConfig_Serialize | PatchRuntimeConfig_Deserialize;

/**  Typed IPC payload for modifying persistent runtime overrides. */
export type PatchRuntimeConfig_Deserialize = {
  'allow-lan'?: boolean | null;
  ipv6?: boolean | null;
  'log-level'?: string | null;
  mode?: string | null;
};

/**  Typed IPC payload for modifying persistent runtime overrides. */
export type PatchRuntimeConfig_Serialize = {
  'allow-lan'?: boolean | null;
  ipv6?: boolean | null;
  'log-level'?: string | null;
  mode?: string | null;
};

export type PendingDeepLinkEntry = {
  id: number;
  url: string;
};

/**  后处理输出 */
export type PostProcessingOutput = {
  /**  Per-source transform chain output, keyed by source profile UID and transform UID. */
  scopes: { [key in string]: { [key in string]: [LogSpan, string][] } };
  /**  Global transform chain output, keyed by transform UID. */
  global: { [key in string]: [LogSpan, string][] };
};

/**  Top-level semantic split. */
export type ProfileDefinition =
  ProfileDefinition_Serialize | ProfileDefinition_Deserialize;

/**  Top-level semantic split. */
export type ProfileDefinition_Deserialize =
  | ({ type: 'config'; config: ConfigDefinition_Deserialize } & {
      transform?: never;
    })
  | ({ type: 'transform'; transform: TransformDefinition_Deserialize } & {
      config?: never;
    });

/**  Top-level semantic split. */
export type ProfileDefinition_Serialize =
  | ({ type: 'config'; config: ConfigDefinition_Serialize } & {
      transform?: never;
    })
  | ({ type: 'transform'; transform: TransformDefinition_Serialize } & {
      config?: never;
    });

export type ProfileDocument =
  ProfileDocument_Serialize | ProfileDocument_Deserialize;

export type ProfileDocument_Deserialize = {
  current?: ProfileId | null;
  global_transforms?: ProfileId[];
  valid: string[];
  items: ProfileItem_Deserialize[];
};

export type ProfileDocument_Serialize = {
  current?: ProfileId | null;
  global_transforms?: ProfileId[];
  valid: string[];
  items: ProfileItem_Serialize[];
};

/**  Stable profile identifier. It is also the key used by [`Profiles::items`]. */
export type ProfileId = string;

/**  One named profile item. */
export type ProfileItem = ProfileItem_Serialize | ProfileItem_Deserialize;

/**  One named profile item. */
export type ProfileItem_Deserialize = {
  uid: ProfileId;
} & ProfileMetadata_Deserialize &
  ProfileDefinition_Deserialize;

/**  One named profile item. */
export type ProfileItem_Serialize = {
  uid: ProfileId;
} & ProfileMetadata_Serialize &
  ProfileDefinition_Serialize;

/**  Public, user-editable profile metadata. */
export type ProfileMetadata =
  ProfileMetadata_Serialize | ProfileMetadata_Deserialize;

export type ProfileMetadataPatch =
  ProfileMetadataPatch_Serialize | ProfileMetadataPatch_Deserialize;

export type ProfileMetadataPatch_Deserialize = {
  name: string | null;
  desc?: string | null;
  custom_name?: boolean | null;
};

export type ProfileMetadataPatch_Serialize = {
  name?: string | null;
  desc?: string | null;
  custom_name?: boolean | null;
};

/**  Public, user-editable profile metadata. */
export type ProfileMetadata_Deserialize = {
  name: string;
  desc?: string | null;
  /**
   *  Provenance flag: `true` when the name was chosen by the user (manual
   *  create or rename) and must not be overwritten by subscription name-sync.
   *  Profiles persisted before this field predate provenance tracking; absence
   *  means user-owned so a refresh cannot silently rename them.
   *  The value is never trusted from an incoming patch — it is set only by
   *  rename detection and name-sync (see `ProfileItem::apply_metadata_patch`).
   *  Only the non-default `false` (an unpinned, sync-eligible profile) is
   *  persisted; a user-owned `true` is left off the wire and restored by the
   *  default, so legacy and user-named documents stay byte-identical.
   */
  custom_name?: boolean;
};

/**  Public, user-editable profile metadata. */
export type ProfileMetadata_Serialize = {
  name: string;
  desc?: string | null;
  /**
   *  Provenance flag: `true` when the name was chosen by the user (manual
   *  create or rename) and must not be overwritten by subscription name-sync.
   *  Profiles persisted before this field predate provenance tracking; absence
   *  means user-owned so a refresh cannot silently rename them.
   *  The value is never trusted from an incoming patch — it is set only by
   *  rename detection and name-sync (see `ProfileItem::apply_metadata_patch`).
   *  Only the non-default `false` (an unpinned, sync-eligible profile) is
   *  persisted; a user-owned `true` is left off the wire and restored by the
   *  default, so legacy and user-named documents stay byte-identical.
   */
  custom_name?: boolean;
};

export type ProfileRemoteOptions = {
  user_agent?: string | null;
  with_proxy: boolean;
  self_proxy: boolean;
  update_interval_minutes: number;
};

/**
 *  Who is responsible for maintaining the locally readable file.
 *
 *  `Remote + External` is unrepresentable: external binding exists only inside
 *  the `Local` branch, while `Remote` owns a managed materialization directly.
 */
export type ProfileSource = ProfileSource_Serialize | ProfileSource_Deserialize;

/**
 *  Who is responsible for maintaining the locally readable file.
 *
 *  `Remote + External` is unrepresentable: external binding exists only inside
 *  the `Local` branch, while `Remote` owns a managed materialization directly.
 */
export type ProfileSource_Deserialize =
  | ({ type: 'local'; binding: LocalBinding_Deserialize } & {
      file?: never;
      option?: never;
      subscription?: never;
      updated_at?: never;
      url?: never;
    })
  | ({
      type: 'remote';
      file: ManagedProfilePath;
      updated_at?: number | null;
      url: string;
      option?: ProfileRemoteOptions;
      subscription?: ProfileSubscriptionInfo;
    } & { binding?: never });

/**
 *  Who is responsible for maintaining the locally readable file.
 *
 *  `Remote + External` is unrepresentable: external binding exists only inside
 *  the `Local` branch, while `Remote` owns a managed materialization directly.
 */
export type ProfileSource_Serialize =
  | ({ type: 'local'; binding: LocalBinding_Serialize } & {
      file?: never;
      option?: never;
      subscription?: never;
      updated_at?: never;
      url?: never;
    })
  | ({
      type: 'remote';
      file: ManagedProfilePath;
      updated_at?: number | null;
      url: string;
      option: ProfileRemoteOptions;
      subscription?: ProfileSubscriptionInfo;
    } & { binding?: never });

export type ProfileSubscriptionInfo = {
  upload?: number | null;
  download?: number | null;
  total?: number | null;
  expire?: number | null;
};

export type Proxies = Proxies_Serialize | Proxies_Deserialize;

export type ProxiesSelectorMode = 'normal' | 'hidden' | 'submenu';

export type Proxies_Deserialize = {
  groups: ProxyGroupItem_Deserialize[];
  /**  2 */
  global: ProxyGroupItem_Deserialize;
  /**  3 */
  direct: ProxyItem_Deserialize;
};

export type Proxies_Serialize = {
  groups: ProxyGroupItem_Serialize[];
  /**  2 */
  global: ProxyGroupItem_Serialize;
  /**  3 */
  direct: ProxyItem_Serialize;
};

export type ProxyGroupItem =
  ProxyGroupItem_Serialize | ProxyGroupItem_Deserialize;

export type ProxyGroupItem_Deserialize = {
  /**  1 */
  hidden?: boolean;
  /**  2 */
  name: string;
  /**  3 */
  all: ProxyItem_Deserialize[];
  /**  4 */
  history: ProxyItemHistory[];
  /**  5 */
  now: string | null;
  /**  6 */
  type: string;
  /**  7 */
  udp: boolean;
  /**  8 */
  icon: string | null;
};

export type ProxyGroupItem_Serialize = {
  /**  1 */
  hidden: boolean;
  /**  2 */
  name: string;
  /**  3 */
  all: ProxyItem_Serialize[];
  /**  4 */
  history: ProxyItemHistory[];
  /**  5 */
  now: string | null;
  /**  6 */
  type: string;
  /**  7 */
  udp: boolean;
  /**  8 */
  icon?: string | null;
};

export type ProxyItem = ProxyItem_Serialize | ProxyItem_Deserialize;

export type ProxyItemHistory = {
  time: string;
  delay: number;
};

export type ProxyItem_Deserialize = {
  name: string;
  history: ProxyItemHistory[];
  all: string[] | null;
  hidden?: boolean;
  now: string | null;
  type: string;
  udp: boolean;
  icon: string | null;
};

export type ProxyItem_Serialize = {
  name: string;
  history: ProxyItemHistory[];
  all: string[] | null;
  hidden: boolean;
  now: string | null;
  type: string;
  udp: boolean;
  icon?: string | null;
};

export type Ranking = {
  dimension: Dimension;
  /**  Distinct values of the dimension among the filtered rows. */
  distinct: number;
  /**  Heaviest first. */
  groups: UsageGroup[];
  /**  The groups ranked after `groups`. */
  other: Usage;
};

/**  Whole bytes per second, rounded down. */
export type Rate = {
  upload: number;
  download: number;
};

export type RemoteProfileImportMode = 'default' | 'direct';

export type RemoteProfileOptionsPatch =
  RemoteProfileOptionsPatch_Serialize | RemoteProfileOptionsPatch_Deserialize;

export type RemoteProfileOptionsPatch_Deserialize = {
  user_agent?: string | null;
  with_proxy: boolean | null;
  self_proxy: boolean | null;
  update_interval_minutes: number | null;
};

export type RemoteProfileOptionsPatch_Serialize = {
  user_agent?: string | null;
  with_proxy?: boolean | null;
  self_proxy?: boolean | null;
  update_interval_minutes?: number | null;
};

export type ReportRequest = {
  query: TrafficQuery;
  /**  What the rankings and the topology order and merge their groups by. */
  metric: Metric;
  /**  One ranking per dimension. */
  rankings: Dimension[];
  /**  Groups per ranking, capped at `MAX_LIMIT`. */
  ranking_limit: number;
  topology: TopologyRequest | null;
};

export type RuleKey = {
  kind: string;
  payload: string;
};

export type RunType =
  /**  Run as child process directly */
  | 'normal'
  /**  Run by Nyanpasu Service via a ipc call */
  | 'service'
  /**  Run as elevated process, if profile advice to run as elevated */
  | 'elevated';

export type RuntimeCommitStatus =
  | 'applied'
  | 'deferred'
  | 'saved_inactive'
  | 'unchanged'
  | 'pending'
  | 'recovery_required';

export type RuntimeInfos = {
  service_data_dir: string;
  service_config_dir: string;
  nyanpasu_config_dir: string;
  nyanpasu_data_dir: string;
};

export type RuntimeInspection = {
  snapshot_id: string;
  revision: string;
  target_core: string;
  root_id: number;
  nodes: RuntimeInspectionNode[];
};

export type RuntimeInspectionContent = {
  yaml: string;
  diff: RuntimeInspectionDiff | null;
  logs: StepLogEntry[];
};

export type RuntimeInspectionDiff = {
  parent_id: number;
  hunks: SnapshotDiffHunk[];
};

export type RuntimeInspectionNode = {
  id: number;
  tag: OperatorTag;
  next: number[];
  has_logs: boolean;
  /**  None means unchanged or no comparison baseline (including independent roots). */
  changed_fields: string[] | null;
};

export type RuntimeTransformDiagnostics = {
  revision: number;
  output: PostProcessingOutput;
  failure: RuntimeTransformFailureDiagnostics | null;
};

export type RuntimeTransformFailureDiagnostics = {
  attempt_revision: number;
  transform_uid: string;
  scope_uid: string | null;
  script_type: ScriptType | null;
  message: string;
};

export type ScriptRuntime = 'javascript' | 'lua';

export type ScriptType = 'javascript' | 'lua';

export type ServiceCompat =
  | { kind: 'unknown' }
  | { kind: 'compatible'; server_version: string }
  | {
      kind: 'incompatible';
      server_version: string;
      required_major: number;
      required_min: string;
    }
  | { kind: 'unparsable'; server_version: string };

export type ServicePhase =
  | 'probing'
  | 'not_installed'
  | 'daemon_stopped'
  | 'installing'
  | 'starting_daemon'
  | 'ready'
  | 'incompatible'
  | 'restarting'
  | 'exhausted'
  | 'uninstalling'
  | 'unknown';

export type ServiceStatus = 'not_installed' | 'stopped' | 'running';

/**
 *  Cached service-host projection for UI consumers. It preserves the service
 *  wire fields while exposing lifecycle phase, compatibility, and runtime ownership.
 */
export type ServiceStatusInfo =
  ServiceStatusInfo_Serialize | ServiceStatusInfo_Deserialize;

/**
 *  Cached service-host projection for UI consumers. It preserves the service
 *  wire fields while exposing lifecycle phase, compatibility, and runtime ownership.
 */
export type ServiceStatusInfo_Deserialize = {
  name: string;
  version: string;
  status: ServiceStatus;
  server: StatusResBody_Deserialize | null;
  phase: ServicePhase;
  compat: ServiceCompat;
  runtime_owned: boolean;
  restart_attempts: number;
};

/**
 *  Cached service-host projection for UI consumers. It preserves the service
 *  wire fields while exposing lifecycle phase, compatibility, and runtime ownership.
 */
export type ServiceStatusInfo_Serialize = {
  name: string;
  version: string;
  status: ServiceStatus;
  server: StatusResBody_Serialize | null;
  phase: ServicePhase;
  compat: ServiceCompat;
  runtime_owned: boolean;
  restart_attempts: number;
};

export type SnapshotDiffHunk = {
  old_start: number;
  old_lines: number;
  new_start: number;
  new_lines: number;
  /**  Unified diff lines, including their space, plus, or minus prefix. */
  lines: string[];
};

export type StatusResBody = StatusResBody_Serialize | StatusResBody_Deserialize;

export type StatusResBody_Deserialize = {
  version: string;
  core_infos: CoreInfos_Deserialize;
  runtime_infos: RuntimeInfos;
};

export type StatusResBody_Serialize = {
  version: string;
  core_infos: CoreInfos_Serialize;
  runtime_infos: RuntimeInfos;
};

export type StepLogEntry = {
  level: StepLogLevel;
  message: string;
};

/**  1:1 with the legacy `LogSpan` wire shape (enhance/utils.rs:18-25). */
export type StepLogLevel = 'log' | 'info' | 'warn' | 'error';

export type StorageEntry = {
  key: string;
  /**  Raw JSON-encoded value string. */
  value: string;
};

/**
 *  Event emitted to all windows when a storage value changes.
 *  Event name: `storage-value-changed-event`
 */
export type StorageValueChangedEvent = {
  key: string;
  /**  The new JSON-encoded value, or `None` if the key was removed. */
  value: string | null;
};

export type Topology = {
  /**  By layer, heaviest first, the merged node last. */
  nodes: TopologyNode[];
  edges: TopologyEdge[];
};

export type TopologyEdge = {
  source: string;
  target: string;
  usage: Usage;
};

export type TopologyNode = {
  /**  Unique over layer and key, see `node_id`. */
  id: string;
  /**  Index into the requested layers. */
  layer: number;
  /**  The dimension value; `None` for the node that merges the layer's remaining nodes. */
  key: string | null;
  usage: Usage;
};

export type TopologyRequest = {
  /**  Two to five distinct dimensions, from the first column to the last. */
  layers: Dimension[];
  /**  Nodes beyond this many per layer merge into one "other" node; `None` keeps them all. */
  limit_per_layer: number | null;
};

export type TrafficFilter = {
  dimension: Dimension;
  value: string;
};

/**  Filters on different dimensions combine with AND; a dimension holds at most one value. */
export type TrafficQuery = {
  range: TrafficRange;
  scope: TrafficScope;
  filters: TrafficFilter[];
};

/**  How far back a query looks; always ends now. */
export type TrafficRange =
  | 'last_hour'
  | 'last6_hours'
  | 'last24_hours'
  | 'last7_days'
  | 'last30_days'
  | 'all';

export type TrafficReport = {
  total: Usage;
  current_rate: Rate | null;
  rankings: Ranking[];
  topology: Topology | null;
};

/**  How long recorded traffic is kept. */
export type TrafficRetention = '1d' | '7d' | '30d' | '90d' | 'forever';

/**  Which connections a query counts: `All` is `Active` plus `Closed`. */
export type TrafficScope = 'all' | 'active' | 'closed';

export type TrafficSummary = {
  last_sample_at: number | null;
  active_connections: number;
  /**  Closed connections within the retention, including those not flushed yet. */
  closed_connections: number;
  current_rate: Rate | null;
};

/**  A named config transformer. Transform profiles are reusable but not activatable. */
export type TransformDefinition =
  TransformDefinition_Serialize | TransformDefinition_Deserialize;

/**  A named config transformer. Transform profiles are reusable but not activatable. */
export type TransformDefinition_Deserialize =
  /**  Declarative YAML overlay/patch. This is the new name for legacy Merge. */
  | ({ type: 'overlay'; source: ProfileSource_Deserialize } & {
      runtime?: never;
    })
  /**  Imperative JS/Lua transform. */
  | {
      type: 'script';
      source: ProfileSource_Deserialize;
      runtime: ScriptRuntime;
    };

/**  A named config transformer. Transform profiles are reusable but not activatable. */
export type TransformDefinition_Serialize =
  /**  Declarative YAML overlay/patch. This is the new name for legacy Merge. */
  | ({ type: 'overlay'; source: ProfileSource_Serialize } & { runtime?: never })
  /**  Imperative JS/Lua transform. */
  | { type: 'script'; source: ProfileSource_Serialize; runtime: ScriptRuntime };

export type TransformKind =
  { type: 'overlay' } | { type: 'script'; runtime: ScriptRuntime };

export type TunStack = 'system' | 'gvisor' | 'mixed';

export type UpdateWrapper = {
  rid: number;
  available: boolean;
  current_version: string;
  version: string;
  date: string | null;
  body: string | null;
  raw_json: any;
};

export type UpdaterState =
  | 'idle'
  | 'downloading'
  | 'decompressing'
  | 'replacing'
  | 'restarting'
  | 'done'
  | { failed: string };

export type UpdaterSummary = {
  id: number;
  state: UpdaterState;
  downloader: DownloadStatus;
};

export type Usage = {
  bytes: Bytes;
  connections: number;
};

/**
 *  Exclusive position for heaviest-first paging of grouped usage: the last group of a page, with
 *  its whole usage, so it places the next page under either metric.
 */
export type UsageCursor = {
  usage: Usage;
  key: string;
};

export type UsageGroup = {
  key: string;
  usage: Usage;
  current_rate: Rate | null;
};

export type UsagePage = {
  total: Usage;
  groups: UsageGroup[];
  /**  Groups ranked after this page. */
  other: Usage;
  next: UsageCursor | null;
};

export type WindowState = {
  width: number;
  height: number;
  x: number;
  y: number;
  maximized: boolean;
  fullscreen: boolean;
};

export type WindowType = 'main' | 'legacy';

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: 'error', error: e as any };
  }
}

type EventEmit<T> = [T] extends [null]
  ? () => Promise<void>
  : (payload: T) => Promise<void>;

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent =
    (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
      cb({
        ...event,
        payload: deserialize ? deserialize(event.payload) : event.payload,
      });
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  };

  const fn = (
    target:
      | import('@tauri-apps/api/webview').Webview
      | import('@tauri-apps/api/window').Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  });

  return Object.assign(fn, base);
}
