/* eslint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
  greet: (name: string) => __TAURI_INVOKE<string>('greet', { name }),
  getSysProxy: () =>
    typedError<GetSysProxyResponse, string>(__TAURI_INVOKE('get_sys_proxy')),
  getProfiles: () =>
    typedError<Profiles_Serialize, string>(__TAURI_INVOKE('get_profiles')),
  /**  later: check in the frontend */
  importProfile: (
    url: string,
    option: {
      /**  see issue #13. must set the builder attr for build the user_agent for client */
      user_agent: string | null;
      /**  subscription update interval */
      update_interval: number | null;
    } | null,
  ) =>
    typedError<null, string>(__TAURI_INVOKE('import_profile', { url, option })),
  viewProfile: (uid: string) =>
    typedError<null, string>(__TAURI_INVOKE('view_profile', { uid })),
  /**  修改profiles的 */
  patchProfilesConfig: (profiles: ProfilesBuilder_Deserialize) =>
    typedError<null, string>(
      __TAURI_INVOKE('patch_profiles_config', { profiles }),
    ),
  updateProfile: (
    uid: string,
    option: {
      /**  see issue #13. must set the builder attr for build the user_agent for client */
      user_agent: string | null;
      /**  subscription update interval */
      update_interval: number | null;
    } | null,
  ) =>
    typedError<null, string>(__TAURI_INVOKE('update_profile', { uid, option })),
  patchProfile: (uid: string, profile: ProfileBuilder_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_profile', { uid, profile })),
  deleteProfile: (uid: string) =>
    typedError<null, string>(__TAURI_INVOKE('delete_profile', { uid })),
  readProfileFile: (uid: string) =>
    typedError<string, string>(__TAURI_INVOKE('read_profile_file', { uid })),
  saveProfileFile: (uid: string, fileData: string | null) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_profile_file', { uid, fileData }),
    ),
  /**  create a new profile */
  createProfile: (item: ProfileBuilder_Deserialize, fileData: string | null) =>
    typedError<null, string>(
      __TAURI_INVOKE('create_profile', { item, fileData }),
    ),
  getVergeConfig: () =>
    typedError<IVerge_Serialize, string>(__TAURI_INVOKE('get_verge_config')),
  patchVergeConfig: (payload: IVerge_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_verge_config', { payload })),
  getClashInfo: () =>
    typedError<ClashInfo, string>(__TAURI_INVOKE('get_clash_info')),
  patchClashConfig: (payload: PatchRuntimeConfig_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_clash_config', { payload })),
  patchClashCoreConfig: (payload: PatchClashCoreConfig_Deserialize) =>
    typedError<null, string>(
      __TAURI_INVOKE('patch_clash_core_config', { payload }),
    ),
  getProxies: () =>
    typedError<Proxies_Serialize, string>(__TAURI_INVOKE('get_proxies')),
  selectProxy: (group: string, name: string) =>
    typedError<null, string>(__TAURI_INVOKE('select_proxy', { group, name })),
  changeClashCore: (
    clashCore:
      | 'clash'
      | 'clash-premium'
      | 'clash-rs'
      | 'mihomo'
      | 'clash-meta'
      | 'chimera-client'
      | 'chimera'
      | 'chimera_client'
      | 'mihomo-alpha'
      | 'clash-rs-alpha'
      | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE('change_clash_core', { clashCore }),
    ),
  getRuntimeYaml: () =>
    typedError<string, string>(__TAURI_INVOKE('get_runtime_yaml')),
  getCoreStatus: () =>
    typedError<[CoreState, number, RunType], string>(
      __TAURI_INVOKE('get_core_status'),
    ),
  urlDelayTest: (url: string, expectedStatus: number) =>
    typedError<number | null, string>(
      __TAURI_INVOKE('url_delay_test', { url, expectedStatus }),
    ),
  getIpsbAsn: () =>
    typedError<IpsbResponse, string>(__TAURI_INVOKE('get_ipsb_asn')),
  invokeUwpTool: () =>
    typedError<null, string>(__TAURI_INVOKE('invoke_uwp_tool')),
  collectLogs: () => typedError<null, string>(__TAURI_INVOKE('collect_logs')),
  collectEnvs: () =>
    typedError<EnvInfo, string>(__TAURI_INVOKE('collect_envs')),
  getCustomAppDir: () =>
    typedError<string | null, string>(__TAURI_INVOKE('get_custom_app_dir')),
  setCustomAppDir: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE('set_custom_app_dir', { path })),
  clashApiGetProxyDelay: (name: string, url: string | null) =>
    typedError<DelayRes, string>(
      __TAURI_INVOKE('clash_api_get_proxy_delay', { name, url }),
    ),
  clashApiGetGroupDelay: (group: string, url: string | null) =>
    typedError<{ [key in string]: number }, string>(
      __TAURI_INVOKE('clash_api_get_group_delay', { group, url }),
    ),
  checkUpdate: () =>
    typedError<
      {
        rid: number;
        available: boolean;
        current_version: string;
        version: string;
        date: string | null;
        body: string | null;
        raw_json: any;
      } | null,
      string
    >(__TAURI_INVOKE('check_update')),
  isPortable: () => typedError<boolean, string>(__TAURI_INVOKE('is_portable')),
  isAppimage: () => typedError<boolean, string>(__TAURI_INVOKE('is_appimage')),
  openThat: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE('open_that', { path })),
  cleanupProcesses: () =>
    typedError<null, string>(__TAURI_INVOKE('cleanup_processes')),
  getServerPort: () =>
    typedError<number, string>(__TAURI_INVOKE('get_server_port')),
  getCoreDir: () => typedError<string, string>(__TAURI_INVOKE('get_core_dir')),
  getServiceInstallPrompt: () =>
    typedError<string, string>(__TAURI_INVOKE('get_service_install_prompt')),
  openAppConfigDir: () =>
    typedError<null, string>(__TAURI_INVOKE('open_app_config_dir')),
  openAppDataDir: () =>
    typedError<null, string>(__TAURI_INVOKE('open_app_data_dir')),
  openCoreDir: () => typedError<null, string>(__TAURI_INVOKE('open_core_dir')),
  openLogsDir: () => typedError<null, string>(__TAURI_INVOKE('open_logs_dir')),
  getCoreVersion: (coreType: ClashCore_Deserialize) =>
    typedError<string, string>(
      __TAURI_INVOKE('get_core_version', { coreType }),
    ),
  updateCore: (coreType: ClashCore_Deserialize) =>
    typedError<number, string>(__TAURI_INVOKE('update_core', { coreType })),
  /**  restart the sidecar */
  restartSidecar: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_sidecar')),
  fetchLatestCoreVersions: () =>
    typedError<ManifestVersionLatest, string>(
      __TAURI_INVOKE('fetch_latest_core_versions'),
    ),
  inspectUpdater: (updaterId: number) =>
    typedError<UpdaterSummary, string>(
      __TAURI_INVOKE('inspect_updater', { updaterId }),
    ),
  getStorageItem: (key: string) =>
    typedError<string | null, string>(
      __TAURI_INVOKE('get_storage_item', { key }),
    ),
  setStorageItem: (key: string, value: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('set_storage_item', { key, value }),
    ),
  removeStorageItem: (key: string) =>
    typedError<null, string>(__TAURI_INVOKE('remove_storage_item', { key })),
  /**
   *  Debug: returns all frontend KV entries (keys with the `web:` prefix).
   *  Internal storage entries used by other subsystems are excluded.
   */
  getAllStorageItems: () =>
    typedError<StorageEntry[], string>(__TAURI_INVOKE('get_all_storage_items')),
  /**
   *  Debug: clears all frontend KV entries (keys with the `web:` prefix).
   *  Internal storage entries used by other subsystems are left intact.
   */
  clearStorage: () => typedError<null, string>(__TAURI_INVOKE('clear_storage')),
  statusService: () =>
    typedError<StatusInfo, string>(__TAURI_INVOKE('status_service')),
  installService: () =>
    typedError<null, string>(__TAURI_INVOKE('install_service')),
  uninstallService: () =>
    typedError<null, string>(__TAURI_INVOKE('uninstall_service')),
  startService: () => typedError<null, string>(__TAURI_INVOKE('start_service')),
  stopService: () => typedError<null, string>(__TAURI_INVOKE('stop_service')),
  restartService: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_service')),
  saveWindowSizeState: (label: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_window_size_state', { label }),
    ),
  createMainWindow: () =>
    typedError<null, string>(__TAURI_INVOKE('create_main_window')),
  createLegacyWindow: () =>
    typedError<null, string>(__TAURI_INVOKE('create_legacy_window')),
};

/** Events */
export const events = {
  storageValueChangedEvent: makeEvent<StorageValueChangedEvent>(
    'storage-value-changed-event',
  ),
};

/* Types */
export type BreakWhenProxyChange = 'none' | 'chain' | 'all';

export type BuildInfo = {
  app_name: string;
  app_version: string;
  pkg_version: string;
  commit_hash: string;
  commit_author: string;
  commit_date: string;
  build_date: string;
  build_profile: string;
  build_platform: string;
  rustc_version: string;
  llvm_version: string;
};

export type ChunkStatus = {
  state: ChunkThreadState;
  start: number;
  end: number;
  downloaded: number;
  speed: number | null;
};

export type ChunkThreadState = 'idle' | 'downloading' | 'finished';

export type ClashCore = ClashCore_Serialize | ClashCore_Deserialize;

export type ClashCoreType =
  | 'mihomo'
  | 'mihomo-alpha'
  | 'clash-rs'
  | 'clash-rs-alpha'
  | 'clash'
  | 'chimera_client';

export type ClashCore_Deserialize =
  | 'clash'
  | 'clash-premium'
  | 'clash-rs'
  | 'mihomo'
  | 'clash-meta'
  | 'chimera-client'
  | 'chimera'
  | 'chimera_client'
  | 'mihomo-alpha'
  | 'clash-rs-alpha';

export type ClashCore_Serialize =
  | 'clash'
  | 'clash-rs'
  | 'mihomo'
  | 'chimera-client'
  | 'mihomo-alpha'
  | 'clash-rs-alpha';

export type ClashInfo = {
  /**  clash core port */
  port: number;
  /**  same as `external-controller` */
  server: string;
  /**  clash secret */
  secret: string | null;
};

export type ClashStrategy = {
  external_controller_port_strategy: ExternalControllerPortStrategy;
};

export type CoreInfos = {
  type: CoreType | null;
  state: CoreState;
  state_changed_at: number;
  config_path: string | null;
};

export type CoreState = 'Running' | { Stopped: string | null };

export type CoreType = { clash: ClashCoreType } | 'singbox';

export type DelayRes = {
  delay: number;
};

export type DeviceInfo = {
  cpu: string[];
  memory: string;
};

export type DownloadStatus = {
  state: DownloaderState;
  downloaded: number;
  total: number;
  speed: number | null;
  chunks: ChunkStatus[];
  now: number;
};

export type DownloaderState =
  | 'idle'
  | 'downloading'
  | 'waiting_for_merge'
  | 'merging'
  | { failed: string }
  | 'finished';

export type EnvInfo = {
  os: string;
  arch: string;
  core: { [key in string]: string };
  device: DeviceInfo;
  build_info: BuildInfo;
};

export type ExternalControllerPortStrategy =
  | 'fixed'
  | 'random'
  | 'allow_fallback';

export type GetSysProxyResponse = {
  enable: boolean;
  host: string;
  port: number;
  bypass: string;
  server: string;
};

export type IVerge = IVerge_Serialize | IVerge_Deserialize;

export type IVerge_Deserialize =
  | ({
      /**  1. 日记轮转时间，单位：天 */
      max_log_files: number | null;
      /**
       *  2. app log level
       *  silent | error | warn | info | debug | trace
       */
      app_log_level: LoggingLevel_Deserialize | null;
      /**  3. theme setting */
      theme_color: string | null;
      /**  4. clash tun mode */
      enable_tun_mode: boolean | null;
      /**  5. set system proxy */
      enable_system_proxy: boolean | null;
      /**  5.1. auto launch on system startup */
      enable_auto_launch: boolean | null;
      /**  5.2. do not show window when app launches */
      enable_silent_start: boolean | null;
      /**  6. windows service mode */
      enable_service_mode: boolean | null;
      /**  6.1. window always on top */
      always_on_top: boolean | null;
      /**  6.2. window size and position */
      window_size_state: WindowState | null;
      /**  6.3. global ui framer motion effects */
      lighten_animation_effects: boolean | null;
      /**  7. 是否使用内部的脚本支持，默认为真 */
      enable_builtin_enhanced: boolean | null;
      /**  8. clash core path */
      clash_core: ClashCore_Deserialize | null;
      /**  9. 支持关闭字段过滤，避免meta的新字段都被过滤掉，默认为真 */
      enable_clash_fields: boolean | null;
      /**  10. Clash 相关策略 */
      clash_strategy: ClashStrategy | null;
      /**  11. set system proxy bypass */
      system_proxy_bypass: string | null;
      /**  11.1. web ui list */
      web_ui_list: string[] | null;
      /**  12. verge mixed port 用于覆盖 clash 的 mixed port */
      verge_mixed_port: number | null;
      /**  23. use a random mixed port on startup */
      enable_random_port: boolean | null;
      /**  13. enable proxy guard */
      enable_proxy_guard: boolean | null;
      /**  15. Check update when app launch */
      enable_auto_check_update: boolean | null;
      /**
       *  16. 切换代理时中断连接
       *  None: 不中断
       *  Chain: 仅中断使用该代理链的连接
       *  All: 中断所有连接
       */
      break_when_proxy_change: BreakWhenProxyChange | null;
      /**
       *  17. 切换配置时中断连接
       *  true: 中断所有连接
       *  false: 不中断连接
       */
      break_when_profile_change: boolean | null;
      /**
       *  18. 切换模式时中断连接
       *  true: 中断所有连接
       *  false: 不中断连接
       */
      break_when_mode_change: boolean | null;
      /**  19. `light` or `dark` or `system` */
      theme_mode: string | null;
      /**  20. i18n */
      language: string | null;
      /**
       *  21. Legacy compatibility field for older configs.
       *  Prefer window_type for new code.
       */
      use_legacy_ui: boolean | null;
      /**
       *  22. Tun 堆栈选择
       *  TODO: 弃用此字段，转移到 clash config 里
       */
      tun_stack: TunStack | null;
      /**  23. show proxies in tray menu */
      clash_tray_selector: ProxiesSelectorMode | null;
      /**
       *  24. Window type to use when opening the app window
       *  Main: opens new main window
       *  Legacy: opens legacy window
       */
      window_type: WindowType | null;
    } & {
      /**  14. proxy guard interval */
      proxy_guard_interval: number | null;
    })
  | {
      /**  14. proxy guard interval */
      proxy_guard_duration: number | null;
    };

export type IVerge_Serialize = {
  /**  1. 日记轮转时间，单位：天 */
  max_log_files: number | null;
  /**
   *  2. app log level
   *  silent | error | warn | info | debug | trace
   */
  app_log_level: LoggingLevel_Serialize | null;
  /**  3. theme setting */
  theme_color: string | null;
  /**  4. clash tun mode */
  enable_tun_mode: boolean | null;
  /**  5. set system proxy */
  enable_system_proxy: boolean | null;
  /**  5.1. auto launch on system startup */
  enable_auto_launch: boolean | null;
  /**  5.2. do not show window when app launches */
  enable_silent_start: boolean | null;
  /**  6. windows service mode */
  enable_service_mode?: boolean | null;
  /**  6.1. window always on top */
  always_on_top?: boolean | null;
  /**  6.2. window size and position */
  window_size_state?: WindowState | null;
  /**  6.3. global ui framer motion effects */
  lighten_animation_effects: boolean | null;
  /**  7. 是否使用内部的脚本支持，默认为真 */
  enable_builtin_enhanced: boolean | null;
  /**  8. clash core path */
  clash_core?: ClashCore_Serialize | null;
  /**  9. 支持关闭字段过滤，避免meta的新字段都被过滤掉，默认为真 */
  enable_clash_fields: boolean | null;
  /**  10. Clash 相关策略 */
  clash_strategy: ClashStrategy | null;
  /**  11. set system proxy bypass */
  system_proxy_bypass: string | null;
  /**  11.1. web ui list */
  web_ui_list: string[] | null;
  /**  12. verge mixed port 用于覆盖 clash 的 mixed port */
  verge_mixed_port: number | null;
  /**  23. use a random mixed port on startup */
  enable_random_port: boolean | null;
  /**  13. enable proxy guard */
  enable_proxy_guard: boolean | null;
  /**  14. proxy guard interval */
  proxy_guard_interval: number | null;
  /**  15. Check update when app launch */
  enable_auto_check_update: boolean | null;
  /**
   *  16. 切换代理时中断连接
   *  None: 不中断
   *  Chain: 仅中断使用该代理链的连接
   *  All: 中断所有连接
   */
  break_when_proxy_change: BreakWhenProxyChange | null;
  /**
   *  17. 切换配置时中断连接
   *  true: 中断所有连接
   *  false: 不中断连接
   */
  break_when_profile_change: boolean | null;
  /**
   *  18. 切换模式时中断连接
   *  true: 中断所有连接
   *  false: 不中断连接
   */
  break_when_mode_change: boolean | null;
  /**  19. `light` or `dark` or `system` */
  theme_mode: string | null;
  /**  20. i18n */
  language: string | null;
  /**
   *  21. Legacy compatibility field for older configs.
   *  Prefer window_type for new code.
   */
  use_legacy_ui: boolean | null;
  /**
   *  22. Tun 堆栈选择
   *  TODO: 弃用此字段，转移到 clash config 里
   */
  tun_stack: TunStack | null;
  /**  23. show proxies in tray menu */
  clash_tray_selector: ProxiesSelectorMode | null;
  /**
   *  24. Window type to use when opening the app window
   *  Main: opens new main window
   *  Legacy: opens legacy window
   */
  window_type: WindowType | null;
};

export type IpsbResponse = {
  organization: string;
  longitude: number | null;
  timezone: string;
  isp: string;
  offset: number;
  asn: number;
  asn_organization: string;
  country: string;
  ip: string;
  latitude: number | null;
  continent_code: string;
  country_code: string;
};

export type LocalProfile = LocalProfile_Serialize | LocalProfile_Deserialize;

/** Builder for [`LocalProfile`](struct.LocalProfile.html). */
export type LocalProfileBuilder =
  | LocalProfileBuilder_Serialize
  | LocalProfileBuilder_Deserialize;

/** Builder for [`LocalProfile`](struct.LocalProfile.html). */
export type LocalProfileBuilder_Deserialize =
  | ({
      symlinks: string | null;
    } & ProfileSharedBuilder & {
        chain?: string[] | null;
      })
  | {
      chains?: string[] | null;
    };

/** Builder for [`LocalProfile`](struct.LocalProfile.html). */
export type LocalProfileBuilder_Serialize = {
  symlinks: string | null;
  chain: string[] | null;
} & ProfileSharedBuilder;

export type LocalProfile_Deserialize =
  | ({
      symlinks: string | null;
    } & ProfileShared & {
        chain?: string[];
      })
  | {
      chains?: string[];
    };

export type LocalProfile_Serialize = {
  symlinks?: string | null;
  chain: string[];
} & ProfileShared;

export type LoggingLevel = LoggingLevel_Serialize | LoggingLevel_Deserialize;

export type LoggingLevel_Deserialize =
  | 'silent'
  | 'off'
  | 'trace'
  | 'tracing'
  | 'debug'
  | 'info'
  | 'warn'
  | 'warning'
  | 'error';

export type LoggingLevel_Serialize =
  | 'silent'
  | 'trace'
  | 'debug'
  | 'info'
  | 'warn'
  | 'error';

export type ManifestVersionLatest = {
  mihomo: string;
  mihomo_alpha: string;
  clash_rs: string;
  chimera_client: string;
  clash_rs_alpha: string;
  clash_premium: string;
};

export type PatchClashCoreConfig =
  | PatchClashCoreConfig_Serialize
  | PatchClashCoreConfig_Deserialize;

export type PatchClashCoreConfig_Deserialize = {
  'mixed-port'?: number | null;
  secret?: string | null;
  'external-controller'?: string | null;
};

export type PatchClashCoreConfig_Serialize = {
  'mixed-port'?: number | null;
  secret?: string | null;
  'external-controller'?: string | null;
};

export type PatchRuntimeConfig =
  | PatchRuntimeConfig_Serialize
  | PatchRuntimeConfig_Deserialize;

export type PatchRuntimeConfig_Deserialize = {
  'allow-lan'?: boolean | null;
  ipv6?: boolean | null;
  'log-level'?: string | null;
  mode?: string | null;
};

export type PatchRuntimeConfig_Serialize = {
  'allow-lan'?: boolean | null;
  ipv6?: boolean | null;
  'log-level'?: string | null;
  mode?: string | null;
};

export type Profile = Profile_Serialize | Profile_Deserialize;

export type ProfileBuilder =
  | ProfileBuilder_Serialize
  | ProfileBuilder_Deserialize;

export type ProfileBuilder_Deserialize =
  | ({
      remote: {
        type: 'remote';
      } & RemoteProfileBuilder;
    } & { local?: never })
  | ({
      local: {
        type: 'local';
      } & LocalProfileBuilder_Deserialize;
    } & { remote?: never });

export type ProfileBuilder_Serialize =
  | ({
      remote: {
        type: 'remote';
      } & RemoteProfileBuilder;
    } & { local?: never })
  | ({
      local: {
        type: 'local';
      } & LocalProfileBuilder_Serialize;
    } & { remote?: never });

export type ProfileShared = {
  /**  Profile ID */
  uid: string;
  /**  profile name */
  name: string;
  /**  profile holds the file */
  file: string;
  /**  profile description */
  desc: string | null;
  /**  update time */
  updated: number;
};

/** Builder for [`ProfileShared`](struct.ProfileShared.html). */
export type ProfileSharedBuilder = {
  /**  Profile ID */
  uid: string | null;
  /**  profile name */
  name: string | null;
  /**  profile holds the file */
  file: string | null;
  /**  profile description */
  desc: string | null;
  /**  update time */
  updated: number | null;
};

export type Profile_Deserialize =
  | ({
      remote: {
        type: 'remote';
      } & RemoteProfile_Deserialize;
    } & { local?: never })
  | ({
      local: {
        type: 'local';
      } & LocalProfile_Deserialize;
    } & { remote?: never });

export type Profile_Serialize =
  | ({
      remote: {
        type: 'remote';
      } & RemoteProfile_Serialize;
    } & { local?: never })
  | ({
      local: {
        type: 'local';
      } & LocalProfile_Serialize;
    } & { remote?: never });

export type Profiles = Profiles_Serialize | Profiles_Deserialize;

/** Builder for [`Profiles`](struct.Profiles.html). */
export type ProfilesBuilder =
  | ProfilesBuilder_Serialize
  | ProfilesBuilder_Deserialize;

/** Builder for [`Profiles`](struct.Profiles.html). */
export type ProfilesBuilder_Deserialize = {
  current: string[] | null;
  /**  profile list */
  items: Profile_Deserialize[] | null;
  /**  record valid fields for clash */
  valid: string[] | null;
  /**  same as PrfConfig.chain */
  chain: string[] | null;
};

/** Builder for [`Profiles`](struct.Profiles.html). */
export type ProfilesBuilder_Serialize = {
  current: string[] | null;
  /**  profile list */
  items: Profile_Serialize[] | null;
  /**  record valid fields for clash */
  valid: string[] | null;
  /**  same as PrfConfig.chain */
  chain: string[] | null;
};

export type Profiles_Deserialize = {
  current: string[];
  /**  profile list */
  items?: Profile_Deserialize[];
  /**  record valid fields for clash */
  valid?: string[];
  /**  same as PrfConfig.chain */
  chain: string[];
};

export type Profiles_Serialize = {
  current: string[];
  /**  profile list */
  items: Profile_Serialize[];
  /**  record valid fields for clash */
  valid: string[];
  /**  same as PrfConfig.chain */
  chain: string[];
};

export type Proxies = Proxies_Serialize | Proxies_Deserialize;

export type ProxiesSelectorMode = 'normal' | 'hidden' | 'submenu';

export type Proxies_Deserialize = {
  groups: ProxyGroupItem_Deserialize[];
  /**  2 */
  global: ProxyGroupItem_Deserialize;
  /**  3 */
  direct: ProxyItem_Deserialize;
};

export type Proxies_Serialize = {
  groups: ProxyGroupItem_Serialize[];
  /**  2 */
  global: ProxyGroupItem_Serialize;
  /**  3 */
  direct: ProxyItem_Serialize;
};

export type ProxyGroupItem =
  | ProxyGroupItem_Serialize
  | ProxyGroupItem_Deserialize;

export type ProxyGroupItem_Deserialize = {
  /**  1 */
  hidden?: boolean;
  /**  2 */
  name: string;
  /**  3 */
  all: ProxyItem_Deserialize[];
  /**  4 */
  history: ProxyItemHistory[];
  /**  5 */
  now: string | null;
  /**  6 */
  type: string;
  /**  7 */
  udp: boolean;
  /**  8 */
  icon: string | null;
};

export type ProxyGroupItem_Serialize = {
  /**  1 */
  hidden: boolean;
  /**  2 */
  name: string;
  /**  3 */
  all: ProxyItem_Serialize[];
  /**  4 */
  history: ProxyItemHistory[];
  /**  5 */
  now: string | null;
  /**  6 */
  type: string;
  /**  7 */
  udp: boolean;
  /**  8 */
  icon?: string | null;
};

export type ProxyItem = ProxyItem_Serialize | ProxyItem_Deserialize;

export type ProxyItemHistory = {
  time: string;
  delay: number;
};

export type ProxyItem_Deserialize = {
  name: string;
  history: ProxyItemHistory[];
  all: string[] | null;
  hidden?: boolean;
  now: string | null;
  type: string;
  udp: boolean;
  icon: string | null;
};

export type ProxyItem_Serialize = {
  name: string;
  history: ProxyItemHistory[];
  all: string[] | null;
  hidden: boolean;
  now: string | null;
  type: string;
  udp: boolean;
  icon?: string | null;
};

export type RemoteProfile = RemoteProfile_Serialize | RemoteProfile_Deserialize;

/** Builder for [`RemoteProfile`](struct.RemoteProfile.html). */
export type RemoteProfileBuilder = {
  /**  subscription url */
  url: string | null;
  option: RemoteProfileOptionsBuilder;
  chain: string[] | null;
  /**  subscription user info */
  extra: SubscriptionInfo | null;
} & ProfileSharedBuilder;

export type RemoteProfileOptions =
  | RemoteProfileOptions_Serialize
  | RemoteProfileOptions_Deserialize;

/** Builder for [`RemoteProfileOptions`](struct.RemoteProfileOptions.html). */
export type RemoteProfileOptionsBuilder = {
  /**  see issue #13. must set the builder attr for build the user_agent for client */
  user_agent: string | null;
  /**  subscription update interval */
  update_interval: number | null;
};

export type RemoteProfileOptions_Deserialize = {
  /**  see issue #13. must set the builder attr for build the user_agent for client */
  user_agent: string | null;
  /**  subscription update interval */
  update_interval: number;
};

export type RemoteProfileOptions_Serialize = {
  /**  see issue #13. must set the builder attr for build the user_agent for client */
  user_agent?: string | null;
  /**  subscription update interval */
  update_interval: number;
};

export type RemoteProfile_Deserialize = {
  /**  subscription url */
  url: string;
  option: RemoteProfileOptions_Deserialize;
  chain: string[];
  /**  subscription user info */
  extra?: SubscriptionInfo;
} & ProfileShared;

export type RemoteProfile_Serialize = {
  /**  subscription url */
  url: string;
  option: RemoteProfileOptions_Serialize;
  chain: string[];
  /**  subscription user info */
  extra: SubscriptionInfo;
} & ProfileShared;

export type RunType =
  /**  Run as child process directly */
  | 'normal'
  /**  Run by Nyanpasu Service via a ipc call */
  | 'service'
  /**  Run as elevated process, if profile advice to run as elevated */
  | 'elevated';

export type RuntimeInfos = {
  service_data_dir: string;
  service_config_dir: string;
  nyanpasu_config_dir: string;
  nyanpasu_data_dir: string;
};

export type ServiceStatus = 'not_installed' | 'stopped' | 'running';

export type StatusInfo = {
  name: string;
  version: string;
  status: ServiceStatus;
  server: StatusResBody | null;
};

export type StatusResBody = {
  version: string;
  core_infos: CoreInfos;
  runtime_infos: RuntimeInfos;
};

export type StorageEntry = {
  key: string;
  /**  Raw JSON-encoded value string. */
  value: string;
};

/**
 *  Event emitted to all windows when a storage value changes.
 *  Event name: `storage-value-changed-event`
 */
export type StorageValueChangedEvent = {
  key: string;
  /**  The new JSON-encoded value, or `None` if the key was removed. */
  value: string | null;
};

export type SubscriptionInfo = {
  upload: number;
  download: number;
  total: number;
  expire: number;
};

export type TunStack = 'system' | 'gvisor' | 'mixed';

export type UpdateWrapper = {
  rid: number;
  available: boolean;
  current_version: string;
  version: string;
  date: string | null;
  body: string | null;
  raw_json: any;
};

export type UpdaterState =
  | 'idle'
  | 'downloading'
  | 'decompressing'
  | 'replacing'
  | 'restarting'
  | 'done'
  | { failed: string };

export type UpdaterSummary = {
  id: number;
  state: UpdaterState;
  downloader: DownloadStatus;
};

export type WindowState = {
  width: number;
  height: number;
  x: number;
  y: number;
  maximized: boolean;
  fullscreen: boolean;
};

export type WindowType = 'main' | 'legacy';

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: 'error', error: e as any };
  }
}

type EventEmit<T> = [T] extends [null]
  ? () => Promise<void>
  : (payload: T) => Promise<void>;

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent =
    (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
      cb({
        ...event,
        payload: deserialize ? deserialize(event.payload) : event.payload,
      });
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  };

  const fn = (
    target:
      | import('@tauri-apps/api/webview').Webview
      | import('@tauri-apps/api/window').Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  });

  return Object.assign(fn, base);
}
