use serde_yaml::Mapping;

use anyhow::Result;
use nyanpasu_utils::runtime::block_on;
use once_cell::sync::OnceCell;

use crate::{
    config::{
        chimera::IVerge, clash::IClashTemp, draft::Draft, profile::profiles::Profiles,
        runtime::IRuntime,
    },
    core::state::ManagedState,
    enhance::{self, PostProcessingOutput},
};

/// whole config
pub struct Config {
    profiles_config: ManagedState<Profiles>,
    verge_config: Draft<IVerge>,
    /// 3
    clash_config: Draft<IClashTemp>,
    /// 4
    runtime_config: Draft<IRuntime>,
}

impl Config {
    pub fn global() -> &'static Config {
        static CONFIG: OnceCell<Config> = OnceCell::new();

        CONFIG.get_or_init(|| Config {
            profiles_config: ManagedState::from(Profiles::new()),
            verge_config: Draft::from(IVerge::new()),
            clash_config: Draft::from(IClashTemp::new()),
            runtime_config: Draft::from(IRuntime::new()),
        })
    }

    pub fn profiles() -> &'static ManagedState<Profiles> {
        &Self::global().profiles_config
    }

    pub fn verge() -> Draft<IVerge> {
        Self::global().verge_config.clone()
    }

    /// Generate the runtime mapping and transform output once from the same enhancement pass.
    pub async fn generate_runtime_input() -> Result<(Mapping, PostProcessingOutput)> {
        let clash = crate::bridge::clash::clash_config_from_legacy(
            &Self::verge().latest(),
            &Self::clash().latest().0,
        )?;
        let (config, _exists_keys, postprocessing_output) = enhance::enhance(&clash).await?;

        *Config::runtime().draft() = IRuntime {
            config: Some(config.clone()),
        };

        Ok((config, postprocessing_output))
    }

    /// Generate the runtime mapping once and retain the exact draft used by the product pipeline.
    pub async fn generate_runtime_mapping() -> Result<Mapping> {
        Self::generate_runtime_input()
            .await
            .map(|(config, _postprocessing_output)| config)
    }

    /// Legacy compatibility entry point for callers that only need the generated draft.
    pub async fn generate() -> Result<()> {
        Self::generate_runtime_mapping().await.map(drop)
    }

    pub fn clash() -> Draft<IClashTemp> {
        Self::global().clash_config.clone()
    }

    pub fn runtime() -> Draft<IRuntime> {
        Self::global().runtime_config.clone()
    }

    /// Serialize the generated mapping exactly once for candidate/check/promote workflows.
    pub fn render_runtime_bytes(config: &Mapping) -> Result<Vec<u8>> {
        let yaml = serde_yaml::to_string(config)?;
        Ok(format!("# Generated by Clash Chimera\n\n{yaml}").into_bytes())
    }

    /// 初始化配置
    pub fn init_config() -> Result<()> {
        crate::log_err!(block_on(Self::generate()));
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use serde_yaml::{Mapping, Value};

    use super::Config;

    #[test]
    fn runtime_render_is_deterministic_and_has_the_product_header() {
        let mut config = Mapping::new();
        config.insert(Value::String("mode".into()), Value::String("rule".into()));

        let first = Config::render_runtime_bytes(&config).unwrap();
        let second = Config::render_runtime_bytes(&config).unwrap();

        assert_eq!(first, second);
        assert!(first.starts_with(b"# Generated by Clash Chimera\n\n"));
        let body = std::str::from_utf8(&first).unwrap();
        assert!(body.contains("mode: rule"));
    }
}
