use serde_yaml::Mapping;

use anyhow::Result;
use chimera_config::clash::config::ClashConfig;
use once_cell::sync::OnceCell;

use crate::{
    config::{
        chimera::IVerge, clash::IClashTemp, draft::Draft, profile::profiles::Profiles,
        runtime::IRuntime,
    },
    enhance::{self, PostProcessingOutput},
};

pub(crate) struct RuntimeInputOutput {
    pub(crate) config: Mapping,
    pub(crate) exists_keys: Vec<String>,
    pub(crate) postprocessing_output: PostProcessingOutput,
    pub(crate) inspection: crate::client::runtime_inspection::RuntimeInspectionData,
}

/// whole config
pub struct Config {
    verge_config: Draft<IVerge>,
    /// 3
    clash_config: Draft<IClashTemp>,
    /// 4
    runtime_config: Draft<IRuntime>,
}

impl Config {
    pub fn global() -> &'static Config {
        static CONFIG: OnceCell<Config> = OnceCell::new();

        CONFIG.get_or_init(|| Config {
            verge_config: Draft::from(IVerge::new()),
            clash_config: Draft::from(IClashTemp::new()),
            runtime_config: Draft::from(IRuntime::new()),
        })
    }

    pub fn verge() -> Draft<IVerge> {
        Self::global().verge_config.clone()
    }

    pub(crate) async fn generate_runtime_output_with_ports(
        clash: &ClashConfig,
        profiles: &Profiles,
        core: crate::config::chimera::ClashCore,
        resolved_ports: chimera_config::runtime::executor::ResolvedPortBindings,
    ) -> Result<RuntimeInputOutput> {
        // All supported cores use the shared ref-aligned executor. Runtime
        // generation has one business implementation; failures are surfaced
        // instead of silently switching to the legacy enhancer.
        let (config, exists_keys, postprocessing_output, inspection) =
            enhance::build_from_legacy_with_inspection(clash, profiles, core, resolved_ports)
                .await?;

        *Config::runtime().draft() = IRuntime {
            config: Some(config.clone()),
        };

        Ok(RuntimeInputOutput {
            config,
            exists_keys,
            postprocessing_output,
            inspection,
        })
    }

    pub fn clash() -> Draft<IClashTemp> {
        Self::global().clash_config.clone()
    }

    pub fn runtime() -> Draft<IRuntime> {
        Self::global().runtime_config.clone()
    }

    /// Serialize the generated mapping exactly once for candidate/check/promote workflows.
    pub fn render_runtime_bytes(config: &Mapping) -> Result<Vec<u8>> {
        let yaml = serde_yaml::to_string(config)?;
        Ok(format!("# Generated by Clash Chimera\n\n{yaml}").into_bytes())
    }
}

#[cfg(test)]
mod tests {
    use serde_yaml::{Mapping, Value};

    use super::Config;

    #[test]
    fn runtime_render_is_deterministic_and_has_the_product_header() {
        let mut config = Mapping::new();
        config.insert(Value::String("mode".into()), Value::String("rule".into()));

        let first = Config::render_runtime_bytes(&config).unwrap();
        let second = Config::render_runtime_bytes(&config).unwrap();

        assert_eq!(first, second);
        assert!(first.starts_with(b"# Generated by Clash Chimera\n\n"));
        let body = std::str::from_utf8(&first).unwrap();
        assert!(body.contains("mode: rule"));
    }
}
