name: Renovate Artifacts
on:
  workflow_call:
    inputs:
      commands:
        description: JSON encoded list of commands Renovate will execute.
        required: true
        type: string

jobs:
  artifacts:
    name: Run Renovate command ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ${{ fromJson(inputs.commands) }}
    steps:
      - name: Prepare Cargo home
        shell: bash
        run: |
          cargo_home="$RUNNER_TEMP/cargo-home"
          if [ -e "$cargo_home" ] && [ ! -d "$cargo_home" ]; then rm -f "$cargo_home"; fi
          mkdir -p "$cargo_home"
          echo "CARGO_HOME=$cargo_home" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: cargo-home-${{ hashFiles('**/Cargo.lock') }}
          root: ${{ github.workspace }}
      - name: Run Renovate command
        shell: bash
        run: ${{ matrix.command }}
