name: '[Entire] Build Release Version'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string
      release_body:
        description: 'Release Body'
        required: false
        type: string

permissions:
  contents: write
  id-token: write

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  macos_aarch64_build:
    name: macOS aarch64 Build
    uses: ./.github/workflows/deps-build-macos.yaml
    with:
      nightly: false
      aarch64: true
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit
  windows_build:
    name: Windows Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    with:
      portable: false
      nightly: false
      # todo:
      fixed-webview: false
      arch: 'x86_64'
      tag: ${{ inputs.tag || github.event.release.tag_name }}
    secrets: inherit
  linux_build:
    name: Linux Build
    uses: ./.github/workflows/deps-build-linux.yaml
    with:
      nightly: false
      tag: ${{ inputs.tag || github.event.release.tag_name }}
      arch: 'x86_64'
    secrets: inherit

  upload_release_assets:
    name: Upload Release Assets
    # todo windows_build
    needs: [windows_build, linux_build, macos_aarch64_build]
    uses: ./.github/workflows/deps-upload-release-assets.yaml
    with:
      tag: ${{ inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [upload_release_assets]
    permissions:
      contents: write
    steps:
      - name: Publish draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ inputs.tag || github.event.release.tag_name }}
        run: |
          gh release edit "$RELEASE_TAG" --draft=false --repo "${{ github.repository }}"

  updater:
    name: Create Updater
    uses: ./.github/workflows/deps-create-updater.yaml
    # todo windows_build
    needs: [publish_release]
    with:
      nightly: false
      release_body: ${{ inputs.release_body || github.event.release.body }}
    secrets: inherit
