name: '[Entire] Build Release Version'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string
      release_body:
        description: 'Release Body'
        required: false
        type: string
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  macos_aarch64_build:
    name: macOS aarch64 Build
    uses: ./.github/workflows/deps-build-macos.yaml
    with:
      nightly: false
      aarch64: true
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit
  upload_release_assets:
    name: Upload Release Assets
    # todo windows_build
    needs: [macos_aarch64_build]
    uses: ./.github/workflows/deps-upload-release-assets.yaml
    with:
      tag: ${{ inputs.tag || github.event.release.tag_name }}
    secrets: inherit
  updater:
    name: Create Updater
    uses: ./.github/workflows/deps-create-updater.yaml
    # todo windows_build
    needs: [upload_release_assets]
    with:
      nightly: false
      release_body: ${{ inputs.release_body || github.event.release.body }}
    secrets: inherit
